### ISSUE TITLE
Isn't this line bad for ensuring the integrity of transactions

### ISSUE THREAD

**Issue by fabercs** [dotnet-architecture/eShopOnWeb#125]
I always see that context's `SaveChanges()` method is isolated inside another function, a `Save()` or a `Complete()` method for the sake of entity framework's **unit of work**  inside generic repository implementations. Here why is it called after for every command methods?

https://github.com/dotnet-architecture/eShopOnWeb/blob/7b24c9140d269d7d670d1e2e0959fab5c9579f3a/src/Infrastructure/Data/EfRepository.cs#L88

**Comment by ardalis** [comment]
This has been discussed before in #46. 
https://github.com/dotnet-architecture/eShopOnWeb/issues/46#issuecomment-412371391

Basically, since the application is typically only performing a single operation per request, there was no need to make it more complex by introducing a Unit of Work pattern (as a separate interface) or adding a `Save()` method on the repository interface(s). But that doesn't mean a more complex application wouldn't benefit from such an abstraction.
