### ISSUE TITLE
Can someone explain to me the difference between services in the Application Core project and the Web project?

### ISSUE THREAD

**Issue by TNHSAesop** [dotnet-architecture/eShopOnWeb#138]
I see the same structure of folders with interfaces and services both in the application core project and the web project.  I'm confused as to why some services and interfaces are in the web project and some are in the application core project.  Doesn't this defeat the purpose of the layered architecture? I do notice that services in the web project seem to be read/query based services that need to have a result pulled into a view model, and the application core services seem to be command only services.  Has this project been extended to include CQRS? I'm trying to implement this type of layered architecture in one of my own apps, but I'm having trouble understanding this part. I downloaded this project based off of reading this article, and now I'm wondering if it's evolved past what was discussed in this article :-/

https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/

Can someone help me understand what the guidelines were for organizing the code this way?

**Comment by ardalis** [comment]
The difference is the kind of services. As you noted, the ones in the web project return things like `ViewModel` types. The ones in the application core work more directly with the domain model and do not have dependencies on or knowledge of UI concerns (including ViewModel types). You can define services in any of the projects, and the decision for where they go should be based on their level of abstraction. As a general rule, if the service has no dependencies on UI or Infrastructure concerns, it should go in Core. Otherwise, put it into the project closest to its dependencies. Try to push as much as you can into Core, because it has the fewest dependencies and thus tends to be easiest to unit test. But don't feel like *every* service must go there.

**Comment by TNHSAesop** [comment]
Thanks for clarification!

**Comment by TNHSAesop** [comment]
It seems that when performing and update or add operation, all code flows through the service layer, even if the service layer just acts as a pass through method to the underlying repository.  However it seems fair to say that in the case of read only operations it's safe to read directly from the repository, bypassing the service layer altogether.  Am I correct in that assessment, and if so why is that?

**Comment by TNHSAesop** [comment]
Maybe I misread the intention, it looks like it could also be the case that if there isn't a need for any business logic for an add or update operation you can use the repository directly.  The service class is only leveraged if there is a need for business logic to be executed before interacting with the repository.  Is that correct?

**Comment by fabercs** [comment]
@ardalis As the project grows up, I came up with that, I have two methods in both ui service and core service which are exact same, eg, `getAllUsers` ui service method for `User/List`, and `getAllUsers` for core service for its logic. So for this scenario, should I keep services as is? Or would it be sensible to call core service from ui service to avoid DRY?

**Comment by ardalis** [comment]
I think you mean to stay DRY, not avoid it. It's up to you. The more business logic you can push into the Application Core, the better. The only reason you typically want to have services in Infrastructure is if they have to deal directly with Infrastructure types. Likewise, services in UI usually are there because they're coupled to the UI in some fashion, such as if they return ViewModel types defined in and only used by the UI project.

**Comment by fabercs** [comment]
yes I meant to avoid repeating yourself. :) Thanks for your remark.
