### ISSUE TITLE
In which project should Localization Resources be?

### ISSUE THREAD

**Issue by fabercs** [dotnet-architecture/eShopOnWeb#146]
I am building an asp.net core app and it should support multi-lang. So, in general, all `.resx` (resource files) reside in `Web` project. I don't think it is a good choice to keep resource files in Web project for this clean architecture approach because, e.g we keep enums which are members to be localized in `Core` project, and core project can not reference `Web` project. So I guess we need to move Resources to the `Core` project, am I right?

**Update**: I think it of again and I can not move Resources files to the Core project as there is  a convention for matching resources via namespaces. So, I guess I should duplicate enums for `Web` project..

**Comment by ardalis** [comment]
There are no enums in this sample, so I'm assuming you're using them just in your own adaptation of this approach. I typically do not use enums when they need to have a display value, preferring instead to use a class-based approach. I have a project here that I use for this purpose: https://github.com/ardalis/SmartEnum

I'd be fine to reference SmartEnum from ApplicationCore since the logic of the classes involved is all part of the business logic / core domain of the app. For localization, that's primarily a UI concern so I would try to keep it in the Web/UI project if possible. If that's difficult or doesn't work, then you could pull it into Core or Infrastructure. Hope that helps.
