### ISSUE TITLE
Repositories of non-aggregate root entities?

### ISSUE THREAD

**Issue by alecola** [dotnet-architecture/eShopOnWeb#160]
Hello,
just a question: why repositories of non-aggregate root entities?

**Comment by vertonghenb** [comment]
A SelectList for example

**Comment by efleming18** [comment]
@alecola @vertonghenb Is this still an issue? Looking through the repositories, I'm not seeing any using `SelectList`.  This is an old issue, and before my time looking at the project so it very well could have been fixed up since then. I will close it for now, but if something is still outstanding, still tag me in this and I can reopen it.
