### ISSUE TITLE
Decoupled UI and DAL

### ISSUE THREAD

**Issue by krs99** [dotnet-architecture/eShopOnWeb#164]
Hello, 
Any news (Issue #25)   regarding decoupled DAL from UI in startup class? Is there any options to use IoC container without tighlty coupled these layers?

**Comment by fiseni** [comment]
ASP.NET Core introduced some changes and improvements, including the built-in service container. By registering services in this container, ASP.NET Core handles all the dependency injection for you. Shortly, IoC is already used in the project.
As far as I can see, most of the logic is already decoupled from DAL. In our case the Web project is the composition root, that's why DAL components are referenced from Startup, but that's the only place where they're referenced. Decoupling in essence means easy replacement, and that indeed is the case here. You can switch the implementations just by replacing the registered service in Startup.

If this approach doesn't meet your expectation, then my suggestion is as following. Let's take Ninject as an example
- Choose a common project, or just create a new one. Place Ninject Kernel class in this project
- Create Ninject module classes on the rest of the projects. Each module will map only the implementations located on that particular project
- In the startup project, load all modules dynamically (e.g. kernel.Load("*.dll"))

Furthermore, if you want even not to reference the projects at all, then you just have to make sure the .dll files are copied in the output build directory. You can achieve that with Post-build events.

**Comment by krs99** [comment]
Thank you for your response.

 I try to avoid use third-party librares as IoC. This sentence is important for me "Decoupling in essence means easy replacement".
 In Web project is a reference to Infrastructure Layer, but there also dependency on Microsoft.EntityFrameworkCore, so I created extensions for IServiceProvider in Infrastructure layer and register services :
`services.AddDbContext<MyDbContext>(options =>
              options.UseSqlServer(connString));`

Now I have at least decoupled Web project from EntityFrameworkCore.

**Comment by efleming18** [comment]
Hey @krs99 - it sounds like you're all set here? Any more questions before I close this issue?

Also, thanks for the reply above @fiseni!

**Comment by krs99** [comment]
I haven't more questions
