### ISSUE TITLE
Organize for feature instead of technology

### ISSUE THREAD

**Issue by motowilliams** [dotnet-architecture/eShopOnWeb#167]
A very common approach for these web apps is to organize them in a way that better aligns with the business value instead of the default technology layout (controllers, models, views etc).

I've yet to have a chat with a product owner where they really want to see how a new controller can drive business value.

**Comment by Dekorg** [comment]
@motowilliams   do you mean something like this  [ContosoUniversityCore/Features](https://github.com/jbogard/ContosoUniversityCore/tree/master/src/ContosoUniversityCore/Features ) ?

**Comment by vertonghenb** [comment]
@Dekorg yes, exactly!

**Comment by ardalis** [comment]
Razor pages allows better organization by feature than Controllers + Views + Models in separate folders do, and this project uses Razor Pages to that end. It also uses Controllers primarily so that it can demonstrate to developers new to the platform how both styles work and how they can both operate side-by-side within a project. This is not that unusual, especially for projects that must serve both page responses as well as host API endpoints.

All that to say, I 100% agree that organizing by feature is the way to go (in fact I have a couple of [MSDN ](https://msdn.microsoft.com/en-us/magazine/mt763233.aspx?f=255&MSPPError=-2147217396)articles on this very topic) but the reason this sample doesn't do that 100% is because it's a sample meant for teaching a variety of concepts, and not an actual business application.

**Comment by motowilliams** [comment]
That's truly unfortunate. The number of production applications based off of "samples" is fairly high.

**Comment by ardalis** [comment]
Well, sure, base it off the sample and then use the bits that work best for you. Another example technology I'd like to demonstrate in a future version is using MediatR, but again it would be side-by-side with approaches that don't use it. We would make sure to add comments in the code as well as coverage in the eBook to call out why this was done and what the various options and tradeoffs are.
