### ISSUE TITLE
What is the role of the IAggregateRoot interface?

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet-architecture/eShopOnWeb#177]
Hi Steve,

I wonder if you could explain the purpose of having the following interface : 
namespace Microsoft.eShopWeb.ApplicationCore.Interfaces
{
    public interface IAggregateRoot
    { }
}
I consider it as an empty interface since there is nothing to implement.

Thanks & Best Regards,
Maher

**Comment by hanslai** [comment]
@MaherJendoubi It is a empty interface,  which used as a marker interface.  Please google for marker interface if you need the definition.

**Comment by ardalis** [comment]
It's a marker interface as @hanslai notes. It can be used to communicate design intent to the development team, and to enforce design decisions. For instance, you could modify your repository interface to only work with IAggregateRoot types, rather than any Entity or BaseEntity types, which would make it much easier to enforce the rule that children in aggregates are never persisted individually, but only as part of the entire aggregate.

**Comment by gregdorian** [comment]
> Hi Steve,
> 
> I wonder if you could explain the purpose of having the following interface :
> namespace Microsoft.eShopWeb.ApplicationCore.Interfaces
> {
> public interface IAggregateRoot
> { }
> }
> I consider it as an empty interface since there is nothing to implement.
> 
> Thanks & Best Regards,
> Maher

@MaherJendoubi  You can also get a good description of an aggregate root class in this thread [https://stackoverflow.com/questions/62647659/purpose-of-iaggregateroot-interface-in-in-microsoft-repository-pattern-document/62647936?noredirect=1#comment111058663_62647936](url) in the answer you can put and Guid in the aggregateRoot.

**Comment by ardalis** [comment]
If you have a Pluralsight sub (or trial sub), Julie Lerman and I cover this in our DDD Fundamentals course.
https://www.pluralsight.com/courses/domain-driven-design-fundamentals

The code sample also makes use of it.

**Comment by 1zerro1** [comment]
Re-opening this... I can't wrap my head around the fact that IReadRepository.cs also implement the IAggregateRoot.  I find it very useful when coupled with IRepository, but often limiting for read operations. I can't find any pitfall where it would potentially create problems reading data with a ReadRepository on an entity that is not an IAggregateRoot.  What am I missing here?

**Comment by ardalis** [comment]
Yeah, that's fair. If you planned on using your ReadRepository for display-only purposes, it would probably be fine to have it access non-aggregate entities. The pattern I prefer for such things is a separate Query object, rather than the Repository, because it allows for more flexibility of return types (Repository should typically only return domain model types - Query objects can return arbitrary query result types). Certainly you should be fine to drop the IAggregateRoot constraint from ReadRepositories, I think.

**Comment by 1zerro1** [comment]
Ah! Fair point for the query object! Thank you for that.
