### ISSUE TITLE
Question: why using repository in web layer

### ISSUE THREAD

**Issue by toronf** [dotnet-architecture/eShopOnWeb#227]
Why you're using specifications in Web and Core layer? This does not make much sense to me. 
On the one site, you're using the Core layer to abstract the UI part. But there is no "clean" line. Sometimes you call repositories direct from Web layer (e.g. ing BasketViewModelService). And sometimes you're using it in the Application layer.

I've seen the comment "there is no business logic there". That would include all direct read operations from DB. 

GetBasketItemCountAsync in BasketService does not contain some business logic as well but it's in the Application layer, not in Web.
Sometimes you're also directly calling the Application services from the cs.html files, without using a service in Web project (e.g. _basketService.AddItemToBasket...). If that is ok, why not using it always and skip the services in Web project?

**Comment by toronf** [comment]
Or is this just to support both, MVC and Razor Pages? In a razor page view model (cshtml.cs) I don't even need to call the services from Web project. It's okay to directly call the services from the core layer from a razor page?

**Comment by efleming18** [comment]
Hey @toronf - Good question, this is a tricky one. The services in the Web project, are really "ViewModel" services. What I mean is they are used for building up the ViewModels from data retrieved by either the repositories or another service in Core. It makes sense to keep them here because we're dealing with ViewModels and the ViewModels need to stay in the Web project, we don't want those leaking over to into the ApplicationCore project. I believe some of the confusion comes from having the classes named "Services" in the Web project? I have some ideas on making this a little more clear and will hopefully have a PR out in the next few days. 

The Services in the ApplicationCore project, don't need to deal with any ViewModels. They mainly just talk to the DB for creation/deletion/retrieval. All of these can safely live outside of the Web project since they don't directly deal with ViewModels.

**Comment by efleming18** [comment]
I renamed the `CatalogService` to `CatalogViewModelService` [in this PR ](https://github.com/dotnet-architecture/eShopOnWeb/pull/233)

Hopefully this helps! I'm going to close this issue.
