### ISSUE TITLE
css/app.css file missing when launched with docker-compose

### ISSUE THREAD

**Issue by kesiena115** [dotnet-architecture/eShopOnWeb#229]
Hi,

I'm running this with 2 different methods:

1. with docker on a mac by running 
```
docker-compose build
docker-compose up
```

2. Debugging in Visual Studio.

When I run in Visual Studio (method 2), it works as expected. However, When I use method 1 with docker-compose, the app is unable to find the app.css file. From Google chrome console, I see this additional error:
```
GET http://localhost:5106/css/app.css net::ERR_ABORTED 404 (Not Found)
```
Could someone please help me understand why this is happening

**Comment by kesiena115** [comment]
I think I've found the problem. To fix this, I had to delete [this line](https://github.com/dotnet-architecture/eShopOnWeb/blob/392b68e89d1ae3afced2e936ba866668816c6581/src/Web/Web.csproj#L12) from Web.csproj. The line is:

```
    <Content Remove="wwwroot\css\app.css" />
```

Why was this added?

**Comment by efleming18** [comment]
@kesiena115 Thanks for catching that and for the way to fix it. I took care of the PR for it. 

As to why it was added, I'm not sure on that. I looked back to the .net core 2.1 branch and it isn't in the Web.csproj file there either so my guess is that it was accidentally added during the .NET Core 2.1 -> 2.2 upgrade. There were other items we saw pop up in the csproj file after the upgrade, and from the research I did they seemed to be bugs in Visual Studio when doing upgrades like that. Looks like we just missed those lines being added.

Thank you for catching that! It should be fixed in master now.
