### ISSUE TITLE
Why add the route named "identity"?

### ISSUE THREAD

**Issue by w152013768** [dotnet-architecture/eShopOnWeb#263]
Why you need to the route named "Identity"? The Project does not include a controller structure with a Identity prefix。

**Comment by efleming18** [comment]
Hey @w152013768 are you referring to these lines? https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Startup.cs#L239-L241

**Comment by w152013768** [comment]
yes, The Project does not include a controller structure with a Identity prefix, why add the route named "Identity". I also have another question: except for the identity under the Area ,why add the "AccountController" in the Controllers, What is the relationship between them?  @efleming18 thanks for help。

**Comment by efleming18** [comment]
I am going to take a deeper look @w152013768 but it does look like those lines in the Startup can likely be removed. They are most likely just left over from upgrading to .NET Core 2.2 as well as consolidating the two projects in to one a few months back.

Similar story with the "AccountController" and the Identity under Areas. Right now we're using the [Microsoft.AspNetCore.Identity NuGet package](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio). This enables us to use it for scaffolding if we need to make custom updates to any of those included in it. As you can see, we've made some custom changes from the default `Login` page included in the package already.

All of the login links/logic when invoked will go through the Login functionality from Areas/Identity/Pages/Account. 

As it sits at the moment though, the Logout/Signout functionality still uses the AccountController. This should likely be moved to use the Identity Razor pages included in the package described above. I will likely have some PRs out to address these items in the next few days. Thanks for bringing it up!

**Comment by w152013768** [comment]
@efleming18 ,thank you for your patient answer, it is very helpful for me! For the first time I actually having got the charm of open source.

**Comment by efleming18** [comment]
No problem at all @w152013768, I'm happy to help. To keep you up to date, this is the [first PR](https://github.com/dotnet-architecture/eShopOnWeb/pull/267) I've created to address what you've pointed out here. What I'm doing in this PR is using the scaffolding provided by the Identity package I mentioned above.

If you're interested in seeing what all is provided in the scaffolding:
- Right click on the **Web** project in the solution
- Select Add -> New Scaffolded Item
- In the dialog that is presented select **Identity** from the menu
- Click "Add"

This will show you everything you can quickly add and use in the project. For this particular PR, I did this and selected **Account\Logout**. After selecting that, in the **Data context class** you'll need to select our Identity DB Context that we use. 

Once you do that, it will generate the new page in **Areas/Identity/Pages/Account/Logout.cshtml**. We can generate this so that we can customize it to fit our needs.

Let me know if you have any questions on this part.

**Comment by w152013768** [comment]
hah, Thanks again.

**Comment by efleming18** [comment]
The last bit, @w152013768, was to cleanup the AccountController, which I did [here](https://github.com/dotnet-architecture/eShopOnWeb/pull/268) for reference. I'm going to close this issue now, but if you have any other questions, please let me know.

**Comment by w152013768** [comment]
@efleming18, I have a suggestion for the project. Before login into the account, I put some things into the basket, but when I have logined or register an account, the basket is empty, Isn't there a shopping cart which I have add to the basket before logined ?
