### ISSUE TITLE
General Architecture: WebAPI Post method

### ISSUE THREAD

**Issue by MukundPrakash** [dotnet-architecture/eShopOnWeb#270]
Thanks for very helpful code.
I am using it for developing one Web API. When I want to Post data should I 1. Create a service in core and call it from controller?
2. Should it be OK if Expose my Core Entity in controller like below:
 [HttpPost]
        public async Task<IActionResult> AddNewTask(TaskEntity object)
{
var taskModel = await _taskServiceCore.CreateTaskAsync(object)
}
I am learning to follow best architecture. Excuse me if that sounds silly.

**Comment by ardalis** [comment]
1. It's up to you if you want to use a service you call from the controller, or if you want to use a repository directly within the controller.
2. Ideally you should not expose your domain model entities to the Internet as API arguments or MVC model binding parameters. The reason is that you may allow an attacker to set properties on the types that you hadn't meant to expose, which could compromise your system or at least allow in bad data. Instead, define specific API models (parameter objects - DTOs) to use for your model binding parameters on your controller action methods.

**Comment by MukundPrakash** [comment]
Thanks @ardalis for giving me DTO pointer. I am exploring DTO and seems like a good fit. If possible please add REST Web API POST operation with DTO using any mapper. That will be very helpful.
Thanks for quick reply. Appreciated.

**Comment by ardalis** [comment]
Can you create a new issue with what you'd like to see an example of, and we'll try and include it? Closing this one now since I think your questions have been answered. Thanks!
