### ISSUE TITLE
Optimization Proposal - Reusing the query of specification

### ISSUE THREAD

**Issue by expressiveco** [dotnet-architecture/eShopOnWeb#271]
For pagination, i need to get the total number records before applying the pagination. So, i do not want the query rebuilt each time; for counting the total number of records and fetching the records for the current page. Thus, i designated the EfRepository.ListForPaging. What do you think about it?

``` c#
public abstract class BaseSpecification<T> : ISpecification<T>
{
    public bool IsPagingEnabled { get; set; } // It is modifiable.
}

public class SpecificationEvaluator<T> where T : BaseEntity
{
  public static IQueryable<T> ApplyPaging(IQueryable<T> inputQuery, ISpecification<T> specification)
  {
      return inputQuery.Skip(specification.Skip).Take(specification.Take);
  }
}
public class EfRepository<T> : IRepository<T>, IAsyncRepository<T> where T : BaseEntity
{
  // TotalCount: Total count of records before paging applied.
  // List: List of records after paging applied.
  public (int totalCount, IEnumerable<T> list) ListForPaging(ISpecification<T> spec)
  {
      // Disable paging to get total count.
      spec.IsPagingEnabled = false;
      var query = ApplySpecification(spec);
      // Get count through query, not specification.
      var totalCount = query.Count();
      // Paging is applied to the existing query so rebuilding the query is eliminated.
      var list = SpecificationEvaluator<T>.ApplyPaging(query, spec).AsEnumerable();

      return (totalCount, list);
  }
}
```
 Usage
``` c#
var filterSpecification = new CategoryFilterPaginatedSpecification(pageIndex, itemsPerPage, queryConstraints);
var (filteredCount, list) = _categoryRepository.ListForPaging(filterSpecification);

```

**Comment by expressiveco** [comment]
I revert ```ISpecification<T>.IsPagingEnabled``` to read-only so i made it through ```SpecificationEvaluator<T>.GetQuery()``` to turn off paging.
So, only following changes required for ``` EfRepository<T>.ListForPaging()```.

``` c#
public class SpecificationEvaluator<T> where T : BaseEntity
{
  public static IQueryable<T> GetQuery(IQueryable<T> inputQuery, ISpecification<T> specification, bool withPaging = true)
  {
      // ...
      // Apply paging if enabled and available.
      if (withPaging && specification.isPagingEnabled)
      {
          query = query.Skip(specification.Skip)
                       .Take(specification.Take);
      }
      return query;
  }
  public static IQueryable<T> ApplyPaging(IQueryable<T> inputQuery, ISpecification<T> specification)
  {
      return inputQuery.Skip(specification.Skip).Take(specification.Take);
  }
}

public interface IRepository<T> where T : BaseEntity
{
    // ...
    (int totalCount, IEnumerable<T> list) ListForPaging(ISpecification<T> spec);
}

public class EfRepository<T> : IRepository<T>, IAsyncRepository<T> where T : BaseEntity
{
  // ...
  private IQueryable<T> ApplySpecification(ISpecification<T> spec, bool withPaging = true)
  {
      if (spec != null)
          return SpecificationEvaluator<T>.GetQuery(_dbContext.Set<T>().AsQueryable(), spec, withPaging, withOrder);
      else
          return _dbContext.Set<T>().AsQueryable();
  }
  // TotalCount: Total count of records before paging applied.
  // List: List of records after paging applied.
  public (int totalCount, IEnumerable<T> list) ListForPaging(ISpecification<T> spec)
  {
      // Disable paging to get total count.
      // Enable ordering because it will be required for the second query.
      var query = ApplySpecification(spec, false);
      // Get count through query, not specification.
      var totalCount = query.Count();
      // Paging is applied to the existing query so rebuilding the query is eliminated.
      var list = SpecificationEvaluator<T>.ApplyPaging(query, spec).AsEnumerable();

      return (totalCount, list);
  }
}
```

**Comment by fiseni** [comment]
Hi @expressiveco.
You are right, to get the total numbers you need separate DB hit. But, are you sure that in your case it happens all within one hit? It seems the following line will generate hit anyway.

`var totalCount = query.Count();`

If your intentions are not to save DB hits, but just to make the code cleaner in the caller, then we might just add additional method in the EfRepository which utilizes the CountAsync() method?
Just a thought.

Cheers

**Comment by fiseni** [comment]
I read your comments once again. Obviously, your concern is building the query twice, not the the round trip to DB. Building the query (as it is done here), is just an in-memory process, and won't affect too much. But, in some super large apps yea it might have an impact. I got your point, I just have few notes
- The method should be async (we should use .CountAsync() instead of Count()). The IRepository is not used anymore.
- AsEnumerable() is a generic method for casting only. It's OK, but if used upon IQueryable, then the query won't be processed at that moment. Instead, it will happen at the caller side, and depending how the results are used, some unexpected errors might occur (e.g. if result is used directly to iterate in for, foreach..).
- Built in tuples are available only in C# 7. I don't know the audience of the project, but folks using VS 2015 might need additional customization in their environment.

**Comment by efleming18** [comment]
Hey @expressiveco - thanks for the interesting question! And thanks to @fiseni for a reply there. I concur with what fiseni's comments are. I know this is more of a question rather than a pull request but I do believe this would be a performance optimization, although, in an app as small as this sample, we wouldn't see the benefits. In a much larger application, we could begin to see that.

It was an interesting way to look at it and optimize it, and I love the use of tuple there!

**Comment by efleming18** [comment]
@expressiveco Is there anything else you need on this? Or is it alright if I close the issue?

**Comment by expressiveco** [comment]
Thanks for your comments. I just want to know if its fine in terms of architecture or OOP.

**Comment by efleming18** [comment]
@expressiveco I don't see why that would be a problem in terms of general architecture or OOP! :)
