### ISSUE TITLE
Maybe moving ViewModels to ApplicationCore is good idea?

### ISSUE THREAD

**Issue by Marius-Kazlauskas** [dotnet-architecture/eShopOnWeb#278]
I want to discuss with you, what do you think about moving ViewModels and related services from Web project to ApplicationCore project?

I see some benefits:
- we can add new web projects like blazor and reuse the same ViewModels and mapping logic
- we can add some other applications like console application for example periodically import some products from text file and then we can reuse the same ViewModels and validation logic of imported product.

Curently I am implementing new project and use ViewModels and related services to ViewModels in ApplicationCore project. Its very interesting to know,  what do you thing about this?

**Comment by ardalis** [comment]
I don't generally like to put ViewModels in Core/ApplicationCore because they're UI concerns, not domain concerns. There is some utility in putting them into a project from which they can be shared, though, sometimes. In such cases I will usually add a 4th project (in addition to core/infrastructure/web) which is an Application layer. It would include ViewModels (and potentially API models, etc.) and services that work with them. When you have a solution that includes this project, your UI projects should be very thin (since most of their application and UI logic can go into this new project) and they generally should have minimal dependencies on low level interfaces that are implemented in infrastructure - instead they would mostly depend on interfaces whose implementations were defined in the Application project.
