### ISSUE TITLE
What should I return from my core services?

### ISSUE THREAD

**Issue by Kleinhummel** [dotnet-architecture/eShopOnWeb#284]
Hey,
i am trying to implement the clean architecture in my own project, but at the moment i don't get any further. I don't know what i should return from my Core Services. I saw that you nearly always return just a Task or a primitive type from your services, but what should i do if i want to return a more complex type?

**Example:**

From my controller i am calling a core service and from the core service i am calling an infrastructure service. The infrastructure service returns a domain entity, because it has a reference to the core project. But what should i return from my core service if i want to return somethin different than a domain entity. After all i am not allowed to map the result to a ViewModel (Dto in my case because i am writing a API) in the core service because the Dtos are in the Web project.

**Closer Example:**
AccountController --> AccountService (Core) --> JwtService (Infrastructure)
The JwtService return a string (The jwt), but in my AccountService i want to return the jwt and the Email of the user. Should i create an extra class for this in the core project? I think this would be a little of an overhead...

I hope you understand my question and can help me :)

Thanks a lot!
Kleinhummel

**Comment by ardalis** [comment]
Core services usually return domain objects (entities, aggregates, maybe value objects) or primitives. Usually the application layer (often combined with the UI layer) is responsible for translating between domain types and UI types (viewmodels, API models, other DTO types). Some teams will put common DTOs in the Core project so they can easily use them from anywhere in the application. The downside to this is only that these typically UI-specific types are now in your domain layer, where they don't necessarily belong, but the effect of this in my experience is pretty minimal.

So, the purist answer is to return domain types and map them to UI types in the application layer. But if you find it works well for you to put DTOs in your Core project, I haven't seen major pain caused by this approach, either.

**Comment by Kleinhummel** [comment]
> Usually the application layer (often combined with the UI layer) is responsible for translating between domain types and UI types

Ah ok, your answer was already quite helpful. But for me, a few things are still a bit unclear.
Do not the core services belong to the application layer? ([Source](http://www.atrenko.com/blog/2018/05/03/clean-architecture/))
I have read many articles about clean architecture now, but I'm not sure how the patterns of the architecture were implemented in this project...So it would be really nice if you answered these questions to me  (@ardalis):

1. Are the core services the same as the Use Case Interactors as described here: [The Clean Architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)?
2. Can I also call a infrastructure service from a controller or should I pass the command to a core service, which passes the command on to the infrastructure service?

**Comment by efleming18** [comment]
Hey @Kleinhummel - hopefully I can help here as well.

1. Reading over that post, it does sound like the User Case interactors are described to be what I would call the Core services. 
2. Typically you're going to want to refrain from calling the infrastructure service directly from the controller and use a service from Core instead. There is usually going to be some sort of business logic that is going to be required in addition to just calling an infrastructure service. You'll want to do this in Core as well to keep the business logic separate from your UI so that when you're ready to return the result to your UI/Controller all you're doing is either passing back a common DTO shared from Core, or mapping the result to something the UI understands.
