### ISSUE TITLE
Foreign Key Generation

### ISSUE THREAD

**Issue by Urgen-Dorjee** [dotnet-architecture/eShopOnWeb#286]
I would like to understand following two tables structure and how "OrderId" foreign key is generated:-

Order Table:-

```
public class Order : BaseEntity, IAggregateRoot
    {
        private Order()
        {
            // required by EF
        }

        public Order(string buyerId, Address shipToAddress, List<OrderItem> items)
        {
            Guard.Against.NullOrEmpty(buyerId, nameof(buyerId));
            Guard.Against.Null(shipToAddress, nameof(shipToAddress));
            Guard.Against.Null(items, nameof(items));

            BuyerId = buyerId;
            ShipToAddress = shipToAddress;
            _orderItems = items;
        }
        public string BuyerId { get; private set; }
        private readonly List<OrderItem> _orderItems = new List<OrderItem>();
        public IReadOnlyCollection<OrderItem> OrderItems => _orderItems.AsReadOnly();

        public DateTimeOffset OrderDate { get; private set; } = DateTimeOffset.Now;
        public Address ShipToAddress { get; private set; }

        public decimal Total()
        {
            var total = 0m;
            foreach (var item in _orderItems)
            {
                total = item.UnitPrice * item.Units;
            }
            return total;
        }
    }
```
OrderItem Table

```
 public class OrderItem : BaseEntity
    {
        public CatalogItemOrdered ItemOrdered { get; private set; }
        public decimal UnitPrice { get; private set; }
        public int Units { get; private set; }

        protected OrderItem()
        { }

        public OrderItem(CatalogItemOrdered itemOrdered, decimal unitPrice, int units)
        {
            ItemOrdered = itemOrdered;
            UnitPrice = unitPrice;
            Units = units;
        }
    }
```

Order Entity Configuration

```
 public class ConfigureOrder : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> builder)
        {
            var navigation = builder.Metadata.FindNavigation(nameof(Order.OrderItems));
            navigation.SetPropertyAccessMode(PropertyAccessMode.Field);
            builder.OwnsOne(o => o.ShipToAddress);
        }
    }


```
Order Items Entity Configuration

```
 public class ConfigureOrderItem : IEntityTypeConfiguration<OrderItem>
    {
        public void Configure(EntityTypeBuilder<OrderItem> builder)
        {
            builder.OwnsOne(i => i.ItemOrdered);
            builder.Property(oi => oi.UnitPrice).IsRequired(true).HasColumnType("decimal(18,2)");
        }
    }
```
OrderItems Table:-

```
Id(PK)
ItemOrdered_CatalogItemId
ItemOrdered_ProductName
ItemOrdered_PictureUri
UnitPrice
Units
OrderId(FK)
```

Please help me to understand how **OrderId(Foreign Key)** has been added into the table structure. I have gone through the above codes but could not figure it out how this FK is generated, when i checked migration file OrderId is reflected under constraints!

**Comment by efleming18** [comment]
Hey @Urgen-Dorjee - good question. The short answer is it's a [shadow property](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties) in EF.

Since the `Order`  model has a reference to the `OrderItem` model, EF Core creates the relationship in the database automatically for you without having to explicitly put `OrderId` on the `OrderItem` model. The relationship is in the way of the foreign key constraint that you pointed out. Something to note though is that this foreign key is actually a nullable foreign key by default. This _is_ something that we should probably change to be a non-nullable foreign key. In order to do that, all we will have to do is explicitly add the `OrderId` property as a non-nullable int to the `OrderItem` model:

`public int OrderId { get; private set; }`

When we create a migration after that, it will update the column's datatype to be a non-nullable `int`.

I will most likely create a PR updating this in the future, but this explains where the `OrderId` column comes from on the `OrderItem` table.
