### ISSUE TITLE
Razor Page vs. View

### ISSUE THREAD

**Issue by trycatchdonothing** [dotnet-architecture/eShopOnWeb#288]
Just curious, why is the Login page a Razor page but the Register page is a view?

**Comment by efleming18** [comment]
Hey @trycatchdonothing - the [Register view](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Views/Account/Register.cshtml) actually needs to be removed as it's no longer the one that is use. Since we're using the [Microsoft.AspNetCore.Identity NuGet package](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio), the pages like Login, Register, etc all use the pages provided by the package. If you need to alter them in any way, you can "add" it to the project via the scaffolding provided. If you're interested in how to add it to the project so that you can alter it, I listed out some steps [here](https://github.com/dotnet-architecture/eShopOnWeb/issues/263#issuecomment-504254329).

I will open an issue to remove this view, and add the Register page via the scaffolding to avoid confusion in the future. If you're interested in contributing feel free, I'll be happy to review a PR! Otherwise, I'll take care of it this week.

Great question and thanks for asking!

**Comment by efleming18** [comment]
I've created an issue for someone to adjust this.
https://github.com/dotnet-architecture/eShopOnWeb/issues/289

I will close this issue shortly, but please feel free to ask any additional questions if you have them.

**Comment by trycatchdonothing** [comment]
Thanks, I actually tried the scaffolding identity UI and it works great. I'm still a little confused about how Razor pages, such as a login page for instance, can be reused in multiple contexts, i.e. a modal window or a full page. Do Razor pages work at all as partials, or no?

**Comment by efleming18** [comment]
Yep! You can use Razor pages as partials. Check out [this article](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-2.2) for some more information!
