### ISSUE TITLE
Question : Services and repositories

### ISSUE THREAD

**Issue by Jaeha90** [dotnet-architecture/eShopOnWeb#293]
Hi,

I just started a new project using repository pattern and I got a question about it.
I have an ItemPriceRepository, an ItemPriceService and an ItemPriceController.

In my ItemPriceController, I need to DI ItemPriceService and ItemPriceRepository, but I'm feeling bad to doing that. To avoid this problem, should I implement every fetching methods from the repository inside the service and using the service only ?

I saw in issue #105 Ardalis talking about keeping the same level of abstraction in controllers. But, for example, when I need to fetch and create something with business logic in the same controller, how do you manage that ?

I hope my question is clear.

Thanks a lot,

Jaeha

**Comment by ardalis** [comment]
There's not necessarily a *right* answer to this question, but for me at least I consider it a "code smell" to have both services and repositories being injected into a class (typically a controller). When I see that, I'll generally pull the repository functionality into the service, as you're describing. But if it's not causing you any pain and would just be more work to do that, don't worry about it! The #1 rule for refactoring is to practice PDD: Pain Driven Development. Don't fix stuff if it's not causing you pain.

That said, what is the benefit of shifting to a service instead of a service + a repository? Mainly it's the abstraction level. Repositories are low level interfaces. They should have no business logic and should only abstract data access. Services, depending on their responsibility, will often do more than that. One thing that you very likely need to do in a controller is map from your business entities (that a repository returns) to some kind of DTOs or viewmodels (that your API will return or that your views will use). This mapping shouldn't happen in your repository - it should return domain entities and shouldn't know anything about UI-level DTOs. But that service could certainly return DTOs, making it so the methods you put in it are not just pass-through methods, but actually perform some valuable work.

HTH.

**Comment by Jaeha90** [comment]
Thank you Ardalis, that's help me a lot :) I'm trying to do a project as clean as possible to be like a "reference project" for the future. Considering that, I will pull repository functionnality in my service, but I will keep in mind that's not a mandatory thing if it's not causing me any pain.

Thanks again for this quick answer.
