### ISSUE TITLE
How to do CRUD on Application User?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#328]
Hello Team,

Can you please assist on a sample to do CRUD on `ApplicationUser`? Let's say an admin to create/update user details? I'm stuck on how to implement this as we have `ApplicationUser` in Infrastructure project with `AppIdentityDbContext` . So all the services, interfaces and specifications needs to be written in Infrastructure project? or `ApplicationUser` needs to be moved to `ApplicationCore` project and should be used with `CatalogContext`?

Thanks,
Abdul Rahman

**Comment by efleming18** [comment]
Hey @fingers10 - I started working on something similar for you (updating existing catalog items via an admin screen), but it still needs a review and possibly some additions/adjustments. Right now, it just allows you to update a few fields for a catalog item. The PR is here: https://github.com/dotnet-architecture/eShopOnWeb/pull/324

For updating user details, have you looked at the "My Account" option in the dropdown after you've logged in? In that screen it allows the user to update their email address. Does that sound like what you're looking for?

**Comment by fingers10** [comment]
@efleming18 . Thanks for your response. 

**My Account** is for an user to update his details. I need something like a admin user to create a end user or activate/deactivate end user so that end user login can be controlled. Any suggestions for this?

**Comment by fingers10** [comment]
@efleming18 any suggestions/helps for this?

**Comment by fingers10** [comment]
@efleming18 any suggestions on where to place the code for my case? To write services on application user it needs to be placed inside `Infrastructure` project? Or any better way to do this with DDD approach?

**Comment by efleming18** [comment]
Hey @fingers10 - I would consider that part of the `Infrastructure` project. The `Infrastructure` project already contains the `AppIdentityDbContext`, `ApplicationUser`, etc.

I could potentially see you wanting to create a separate project for user management if the project as a whole was large enough and this logic needed to be reused in multiple places, but that scenario seems more rare.

**Comment by efleming18** [comment]
Hey @fingers10 - I was thinking on this a little bit more. To build out something like what you're talking about you're most likely going to be leveraging the existing [UserManager](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1?view=aspnetcore-3.0) and [RoleManager](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.rolemanager-1?view=aspnetcore-3.0) Identity services. When you use these, there most likely won't be any custom services you have to write to interact with the database, because most, if not all, functionality should be provided for you already.

You likely don't need to create any Services in Core/Infrastructure projects to build what you're wanting. You may want to pull some of the logic out of the controllers in to a MediatR handler, or some service _	inside_ of the Web project but that would be about it.

Does that help?

**Comment by efleming18** [comment]
@fingers10 does that help? Do you need anything else on this issue?

**Comment by fingers10** [comment]
@efleming18 Sorry for the delayed response. Thanks for your opinions. That was a great help from your end. I'll work on these. I'm good with these now. This can be closed. I'll reopen if I need any further clarifications.

**Comment by efleming18** [comment]
Perfect! Sounds good.
