### ISSUE TITLE
Integration test (LogsInSampleUser) tosses an exception but reports test as succeeded 

### ISSUE THREAD

**Issue by justSteve** [dotnet-architecture/eShopOnWeb#330]
I'm debugging/stepping thru LogsInSampleUser and seeing an exception tossed before the ASSERT statement is hit - yet the test is reported to be green. 

Am new to unit tests (for shame) and curious how that can happen.
The error is at 
> var userManager = scopedServices.GetRequiredService<UserManager<ApplicationUser>>();

Is the problem specific to my local install or can it be reproduced by others?
[note 1 that i'm working against the core3 branch]
[note2 running the web app in browser everything seems to work correctly]

```

{"No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.eShopWeb.Infrastructure.Identity.ApplicationUser]' has been registered."}
"   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)\r\n   at Microsoft.eShopWeb.IntegrationTests.Repositories.OrderRepositoryTests.LoginService.<LogsInSampleUser>d__0.MoveNext() in C:\\Users\\steve\\source\\repos\\CleanArch\\tests\\IntegrationTests\\LoginService.cs:line 35"
```

**Comment by efleming18** [comment]
Hey @justSteve - sorry for the delay. I will take a look at this today.

**Comment by efleming18** [comment]
Hey @justSteve - after reviewing that test further, I am going to just entirely remove this test and here's why:

1. We aren't testing much, or really any, of _our_ code. The test is only using the `UserManager` and the `SignInManager`, both of which are owned by `Microsoft.AspNetCore.Identity` and _we_ shouldn't be responsible for writing those tests.
2. We have a FunctionalTest, `AccountControllerSignIn.ReturnsSuccessfulSignInOnPostWithValidCredentials` which provides more value because it's using the `CustomWebApplicationFactory` which uses the Startup of the actual Web project. This test ensures the same logic, it will ensure the user can login successfully. 
3. The way the test was written initially with a try..catch, unless the test succeeds (so that _it can actually run the `Assert`s_), you won't ever notice that the test is failing (but returning a false-positive) in the exception case, which is what initially brought your question up in the first place. We should avoid using try..catches in unit tests.
4. There were two underlying reasons why the test was failing as it was written anyways. There is additional (Start/Services) configuration that both the `UserManager` and `SignInManager` require in order for them to work. When you use the `CustomWebApplicationFactory`, all of the configuration is already taken care of (In `Startup.cs` and `Program.cs`) for you from the Web project so you're using _exactly_ what you should be using. 


Thanks for pointing this out, and hopefully my response gives you some clarity. I will be pushing the change up to remove that test shortly.
