### ISSUE TITLE
Naming of test methods

### ISSUE THREAD

**Issue by mrukas** [dotnet-architecture/eShopOnWeb#336]
I noticed that the naming of the test methods is not consistent in the whole repository. It may improve readability and orientation while navigating through the tests.

Maybe you could stick to a schema like the one mentioned here:
https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#naming-your-tests

Thanks for maintaining this repository. It is really a great guide.

**Comment by dhulwells** [comment]
I'm willing to take this on if maintainers are looking to make the change.

**Comment by efleming18** [comment]
@dhulwells @mrukas I would certainly be open to reviewing a PR to make everything consistent.

**Comment by efleming18** [comment]
@dhulwells If you take this one, I would like to use a pattern we already have in place and we can use the [BasketServiceTests](https://github.com/dotnet-architecture/eShopOnWeb/tree/master/tests/UnitTests/ApplicationCore/Services/BasketServiceTests) as a template. 

In this we have a folder for the **Service** being tested, and then a new class per method inside of the service. The method name should be in the test class name.

Much of the system seems to mostly conform to that already, so let's make this style consisted across the board.

**Comment by mrukas** [comment]
@efleming18 Is there a reason you choose to create one class per method instead of one test class per class? I just think of larger projects where this would probably create a huge amount of files. I'm just curious.

**Comment by ardalis** [comment]
I can take this one. There are many reasons to prefer having tests organized around the method they are testing:

- Tests for the same method tend to be more similar to one another than tests for a given class
- Putting the test method name in the class name cuts down on useless repetition of the tested method name in each test method
- Because of the above, test classes follow SRP better and are more DRY
- Common set up for the method being tested can be done in standard class setup instead of having to use different helpers-per-method-being-tested
- All tests for a given method are always grouped together; in a long suite of tests that target multiple methods in a class it's not unusual to have different methods' tests mixed together

Reasons to avoid:
- More files.

Which are easily dealt with using folders.

I've organized large projects both ways and have found that, not unlike the app itself, if you follow SOLID and DRY principles for your tests it leads you to more, smaller, more-focused classes. These classes are easier to quickly understand and easier to refactor, move, etc. than large classes (a well-known and common code smell). The only thing developers must get used to is how to navigate solutions that have more, smaller files. Once developers are comfortable with this, the overall effect is in my experience very positive.

**Comment by mrukas** [comment]
Thanks for the explanation! These are good arguments for this structure.
@efleming18, @ardalis 
The tests for the BasketService are also using two different types of naming.
For example: Should_InvokeBasketRepositoryDeleteAsync_Once and ThrowsGivenNullAnonymousId.
Which naming schema do you think should be kept.

**Comment by efleming18** [comment]
Good call out, @mrukas . I think we should follow the `ThrowsGivenNullAnonymousId` schema. The underscores help with readability but I don't think they are necessary and can make the class name longer.

I agree about "Should" being redundant and not needed.

**Comment by efleming18** [comment]
Hey @dhulwells or @mrukas - were either you still planning to work on this one? If not, that is totally fine, I have no problem taking it on but I wanted to give you the opportunity first if you still wanted to work on it.

**Comment by dhulwells** [comment]
I was looking to take it on, but I thought @mrukaa picked it up. I’m
definitely up for it.

**Comment by mrukas** [comment]
Sorry I thought @dhulwells is taking this task. I also doesn't have much time at the moment.

**Comment by dhulwells** [comment]
OK. I’ll take this one on....

**Comment by efleming18** [comment]
Sounds great @dhulwells !

**Comment by mrukas** [comment]
@dhulwells Thanks! Thats great!

**Comment by efleming18** [comment]
Hey @dhulwells  - I'm going to go ahead and take this one!
