### ISSUE TITLE
How to set Web API unit test to different enviorment variable ? 

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnWeb#337]
My tests seem to use Development by default... But I want it to use 'Local'

How do I change CustomWebApplicationFactory to do this ?

**Comment by efleming18** [comment]
Hey @punkouter2018 - does [this doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#environments) help?

If you're trying to set the environment variable, see [this section specifically ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#set-the-environment).

[This](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#set-the-environment) may also help.

[I recently made a change](https://github.com/dotnet-architecture/eShopOnWeb/pull/335) so that the `CustomWebApplicationFactory` would use the `Testing` environment instead of `Development`.

Please let me know if you have further questions! Hopefully this helps.

**Comment by punkouter2018** [comment]
builder.UseEnvironment("Testing");

That's all ?  Ill give that a try tomorrow.

**Comment by efleming18** [comment]
If I am understanding your question correctly, that should be it!

**Comment by punkouter2018** [comment]
yes it works.. One strange thing I don't understand about the CustomWebApplicationFactory is it sets up the EfCore to use inmemory but then uses the connection string from the    builder.UseEnvironment("Local");

is this ignored?

  services.AddDbContext<PwdrsContext>(options =>
                {
                    options.UseInMemoryDatabase("Pwdrs");
                    options.UseInternalServiceProvider(provider);
                });


Now that I think of it I assume I should just be using that over any connection string.

**Comment by efleming18** [comment]
You could set it in either place. You could use the InMemoryDatabase set up from the `Startup.cs` or in the `CustomWebApplicationFactory`. Right now, whatever is in the `CustomWebApplicationFactory` would overwrite whatever is in the `Startup.cs` since we explicitly define it.

Since we're setting it in `CustomWebApplicationFactory`, The `ConfigureTestingServices` method could really become:

```
public void ConfigureTestingServices(IServiceCollection services)
{
    ConfigureServices(services);
}
```

**Comment by punkouter2018** [comment]
Im still confused.. I traced the code for a simple web test..

First, it just to the startup and the DbContext is

            services.AddDbContextPool<PwdrsContext>(o => o.UseSqlServer(Configuration.GetConnectionString("PwdrsConnectionRoot")));


Then it run the code in the CustomWebApplicationFactory and the code says

  services.AddDbContext<PwdrsContext>(options =>
                {
                    options.UseInMemoryDatabase("Pwdrs");
                    options.UseInternalServiceProvider(provider);
                });


Then the unit test runs and it use the SQL DATABASE (from the startup) .. 

Why isnt it using the in memory ?  I thought the point of 

  services.AddDbContext<PwdrsContext>(options =>
                {
                    options.UseInMemoryDatabase("Pwdrs");
                    options.UseInternalServiceProvider(provider);
                });

was to say.. ignore the startup since these are unit tests and just do everything in memory..

??

**Comment by efleming18** [comment]
Hey @punkouter2018 - what environment do you have it configured to use? As in, when you enter in to the `Startup.cs`, it should be using the `ConfigureTestingServices` method. The only way to even configure the SQL server version is if `ConfigureProductionServices` is called - which it shouldn't for tests. 

Regardless though, your tests should be using the InMemoryDatabase if it is being wired up in the `ConfigureServices` call in the `WebApplicationFactory`.

Would you be able to commit your changes to a branch, and I can take a look at it?

**Comment by punkouter2018** [comment]
My code is a mix of this and some other code.. 

So I have it configuring as needed in the Startup.cs but I am wondering what is the point then of the CustomWebApplicationFactory setting the DbContext to inmemory if that's already being set in the Startup.cs ?  

I hope my question makes sense.... I have it working... I just can't understand why the DbContext is set in two places.

**Comment by efleming18** [comment]
You don't need it in two places. Now that we have the `ConfigureTestingServices` in Startup, we could even remove [these lines](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/tests/FunctionalTests/Web/WebTestFixture.cs#L31-L41) and the tests would still work because we're wiring up the in memory databases for both Catalog and Identity. Using `ConfigureTestingServices` for this repo was a recent change, so I will consider removing the lines from `WebTestFixure` (formerly `CustomWebApplicationFactory`) to avoid confusion in the future.

**Comment by punkouter2018** [comment]
I see so those lines are now obsolete becase it gets the connection fron the startup... So in the factory I just pass the env I want so the startup with use whatever db (or in memory connection I want)..

I would assume in the case of the web tests I would always want to use the inMemory database right ? now that I think about it..

**Comment by efleming18** [comment]
> I see so those lines are now obsolete becase it gets the connection fron the startup... So in the factory I just pass the env I want so the startup with use whatever db (or in memory connection I want)..

Correct.

> I would assume in the case of the web tests I would always want to use the inMemory database right ? now that I think about it..

This is more of a personal preference. I've seen teams use InMemory databases, LocalDb, sql server express, etc. There are pros/cons to each.

_At a very high level_: 
InMemory is easy to use and set up and you don't have to worry about cleanup but InMemory DBs don't enforce key constraints, indexes, etc so there _could_ be integration tests you write that work against an in memory DB but wouldn't work in a real DB because of such constraints.

LocalDb is a little more work to get setup, although it's easier now that it ships right with Visual Studio. With this you're _much_ closer to seeing how a real DB would react but you have to worry about cleaning up test data.

I can expand further on this if you'd like, but the short of it is... it depends on what works best for you!

**Comment by punkouter2018** [comment]
ok.. so for the purposes of my basic test Ill create a 'ImMemory' env variable and pass that and use inmemory. got it
