### ISSUE TITLE
Is the way you seed the data obsolete?  

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnWeb#347]
I am told the proper way is use modelBuilder and hasData ? 

I asked a questions about it here 

https://stackoverflow.com/questions/59721251/proper-way-to-update-data-in-lookup-tables-with-efcore-asp-net-core-do-i-do-t

I am trying to figure out the correct way to have the code so that on new releases I can seed data as well as change the model

**Comment by efleming18** [comment]
Hey @punkouter2018 - good question. 

For me, the answer is that it depends on what type of data you're trying to seed.

If you want to seed production data, then you should use `HasData` from within the ModelBuilder. This is data that you always want and need to have in all environments. Keeping track of this data using `HasData` gives you the ability to keep it up-to-date with migrations. I would definitely recommend this route for that type of data.

If you are seeding just test data for local development for example, you would take the approach you have posted in your SO post. This is data that you only care about/need for local testing. For example, maybe you wanted to create a few test users, or a few test records so you have them ready for local debugging. This is data you would want to seed the way we do it and the way you have it in your SO post.

I will take a look at this repository and see if there is anything I could pull out that we would always want to have in each environment, including production. Since this demo app isn't deployed anywhere, that's likely why we've never had anything pulled out in to `HasData`.

~Additional Info
Based on your SO question, it looks like you would want to use the `HasData` approach since those records are wanted/needed in each environment. Whenever you need to add more data to it, you just add another line in the `HasData`, and the migration will pick it up on the next run.

**Comment by punkouter2018** [comment]
We are still months from deploying to production so would it be ok to

1. Until we get to v1 just continue seeding the data as you do in this repo

2. The final week of development move the seeding data into Modelbuilder (I am not sure how different the actual code will be)

I like to develop without dealing with migration files

**Comment by punkouter2018** [comment]
Actually maybe I am wrong. OnModelCreating is done I think form context.database.EnsureCreated() so I guess there's no reason to not just move all the seeding for the LOOKUP tables to there... And there for the DATA tables I could optionally have that run as needed..

**Comment by punkouter2018** [comment]
I am wrong again.. I forgot if I use HasData then I MUST run the Add-migration and then have the .Migrate() to get the data in.. so that's a annoying extra step

**Comment by efleming18** [comment]
It is an extra step, but even with that I would probably recommend to move it over in to HasData sooner rather than later so you don't run in to any unexpected issues the week before you go to production, but that may just be a personal preference of mine.

**Comment by efleming18** [comment]
@punkouter2018 I'm going to close this issue. If you have further questions or anything let me know! We can either reopen this issue, or you can create a new one.
