### ISSUE TITLE
How to update order items after the order has been placed as per DDD?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#358]
I'm trying to understand the best way to update collection of entities inside an aggregate using DDD approach. 

Let's take `Order` and `OrderItems` as an example here and the scenario be like user placed an order with few items. Now the user needs to update the `Order` like making changes to some basic details like address update, etc and also modify the `OrderItems` like removing an item from the list, adding new item to list and updating an existing item in the list.

I have added a method `UpdateDetails` inside `Order` class to update the basic details like address update, etc. Now how to handle the changes to `OrderItems` for above scenario and persist to database? I was thinking to add another method named `UpdateOrderDetails` and pass the list of `OrderItems` and iterate each `OrderItem` and do the following,

1. If the `OrderItem` already exists in the list, then update.
2. If the `OrderItem` not in the list, then create (add to list).
3. After the above two process, remove the `OrderItem` from existing list that are not available in the new list i.e. delete.

or I can directly replace the `OrderItems` inside the `Order` class with the `new OrderItems` list?

Please assist and correct me if I'm wrong.

**Comment by efleming18** [comment]
Hey @fingers10  - I think what you've described makes sense from a DDD perspective. I would maybe recommend calling it `UpdateOrderItems` instead of `UpdateOrderDetails` if you're going to just be passing in and working with the `OrderItems`? In this repo, we do something similar but instead of "OrderItems" we're doing it within the `BasketItems` within the `Basket` aggregate - [here](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/BasketAggregate/BasketItem.cs#L18). 

So, I think you're certainly on the right track.

**Comment by fingers10** [comment]
Thanks for the assistance.
