### ISSUE TITLE
Issue related to connection string

### ISSUE THREAD

**Issue by shailajayadav** [dotnet-architecture/eShopOnWeb#367]
Can someone help me with the example of connection string. How to provide it? 
And I also i wanted to have database on AWS RDS but not able to figure out what's the right way to provide connection string.

**Comment by efleming18** [comment]
Hey @shailajayadav - I might need a little more information to completely answer your question but I'll try to help out the best I can. 

The connection strings for the application are specified in the [appsettings.json file](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/appsettings.json) in the `ConnectionStrings` section. For example, what is checked in to source control now would connect to a localdb instance (mssqllocaldb) locally. In order to use this database, and NOT an in memory database you would need to swap the two lines [here](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Startup.cs#L40). 
Comment out:
`ConfigureInMemoryDatabases(services);`
And uncomment:
`ConfigureProductionServices(services);`

There are many variables on determining the right connection string to be used to connect to any type of database (whether it lives in Azure, or AWS). I would need to know more about the security around it the DB to be able to accurately give guidance on what it should look like. For Azure, if you were using something like Azure SQL it typically will provide you with connection strings to just copy/paste. Check out this doc [here](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connect-query-dotnet-core#get-sql-server-connection-information).

For AWS there is usually a similar "Security and Connectivity" page, but you may have to piece it together.

Does this help?

**Comment by shailajayadav** [comment]
Yes it does help. Just to clear out. I need to create SQL database and provide its connection string with two different Initial Catalog ? 
After that when i run below command its create two different database?
`dotnet restore`
`dotnet tool restore`
`dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj`
`dotnet ef database update -c appidentitydbcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj`

**Comment by shailajayadav** [comment]
it helps. Now its working for me. Thanks for your quick response

**Comment by efleming18** [comment]
That is great to hear @shailajayadav! I'm going to close this issue then. If anything else comes up or you have any more questions, please don't hesitate to reach out.
