### ISSUE TITLE
What if we need to update quantity, or remove the order item

### ISSUE THREAD

**Issue by sattha** [dotnet-architecture/eShopOnWeb#373]
According to this implementation

[https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/OrderAggregate/Order.cs](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/OrderAggregate/Order.cs)

Order.cs which is Aggregate Root, manage the other Entity, and ValueObject. let say if I want to update or delete the quantity for one **OrderItem** that already added, from the AggregateRoot, do I need to do iteration for finding the OrderItem and then update the value?

if yes, look like it causes unnecessary iteration operation. if OrderItem has accessible to mutate directly it would not need to do so.

if no, what is the way to manage this use-case?

**Comment by efleming18** [comment]
Hey @sattha - for updating an Entity itself, you can absolutely put the methods on the Entity class and mutate the entity directly. 

But, if you're adding/deleting items from a collection that should be done through the aggregate.

An Aggregate manages the list of items. The entities manage themselves.  

For example, if you wanted to modify the `CatalogItemOrdered` on the `OrderItem`, you could go directly to the `OrderItem` and perform your operations rather than going through `Order` as well. [BasketItem](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/BasketAggregate/BasketItem.cs) is an example of the entity performing some actions against itself directly.

If you wanted to add/remove an `OrderItem`, you would want to do that through the `Order` aggregate root since it deals w/ the collection of `OrderItems`. 

Does this help?

**Comment by efleming18** [comment]
Hey @sattha - I'm going to close this issue. If you have further questions, either comment here and I can re-open or feel free to open a new issue w/ additional questions.

**Comment by flfaure-pro** [comment]
Hi @efleming18 - Sorry to reopen this closed discussion but I'd like to have a clarification about performing an operation on the entity directly. What if it has an impact on the aggregate root ?

For example in this [file](https://github.com/dotnet-architecture/eShopOnWeb/blob/main/src/ApplicationCore/Services/BasketService.cs):
On line 58, a new quantity is set by calling a method against the basket item entity directly. Then on line 61, a method is called against the aggregate root to clear empty items.
Between those 2 calls, I have the feeling that the aggregate is in a non consitent state. On the application layer, someone could add codes to update a line quantity to 0, without clearing the empty items then, and persist the aggregate.

One solution could be to add a rule to check if the new quantity is equals to 0 and rather call an aggregate root method to remove the item.
But more generally, in DDD, how can I deal with potential entity change that could impact the aggregate root ?
