### ISSUE TITLE
What is the reason for mocking the basket and not using a real one?  

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnWeb#391]
In this BasketBuilder that is used in a repo test. Why is a Mock being used of the Basket object?  

`  public Basket WithOneBasketItem()
        {
            Mock<Basket> basketMock = new Mock<Basket>(BasketBuyerId);
            _basket = basketMock.Object;
            _basket.AddItem(2, 3.40m, 4);
            return _basket;
        }`

**Comment by efleming18** [comment]
Hey @punkouter2018 - A "mock" basket is being used just so we can easily get a Basket created and start from a known state. In this case, we're starting with a basket that has one basket item in it. 

The test that it is being used in, is testing the functionality of when the quantity of an item in an existing basket goes to 0, that the item is completely removed from the basket all together (i.e. removing it, not just setting the quantity to 0). In this test, we don't necessarily care how or where the basket came from, the purpose of the test is only to test the `SetQuantities` functionality - and for that we _are_ using the real `_basketRepository`, and real `basketService`. That's why we can just use a Mock to create the Basket - it's just a piece of test data in this test that we wouldn't want to give us issues as it's not the specific point of the test. 

Does that answer your question?

**Comment by escalonn** [comment]
It doesn't seem to me that Mock here offers any decoupling advantages at all because you're mocking a class and not an interface. The mock object will have all the behavior of the Basket class, so if that behavior had any issues, then the mock basket will have them too. This is just adding extra moving parts for no reason.

**Comment by punkouter2018** [comment]
So the main idea is to use a Mock to imply that it doesnt really matter what is going on with the core domain logic for the basket since we are not interested in testing that ?

**Comment by efleming18** [comment]
@punkouter2018 - that's the general idea behind using a Mock, yes. A mock would be used to override something on a class, or to make sure it returns the exact same result each time you use it. 

@escalonn  brings up a good point though - looking more closely at when this was changed to use a Mock, I'm not sure that Mock really gets us anything here. You can certainly just new up a Basket in this helper. Looking further to the other Builders in the Unit Test project, they do not use Mocks. This _should_ be the same across the board in my opinion, and in this instance I don't think we gain anything from using a Mock here. 

With that said, I'm going to be doing some refactoring of the Tests here: https://github.com/dotnet-architecture/eShopOnWeb/issues/336 so I can update this class back to using the real Basket rather than a Mock.
