### ISSUE TITLE
implementing localization and globalization 

### ISSUE THREAD

**Issue by abdalhadi** [dotnet-architecture/eShopOnWeb#423]
Please how can we implementing localization and globalization to eShopOnWeb.
Do we have resources files, and what is the right place to add them; is it in core or presentation layer?

**Comment by fiseni** [comment]
This is a tricky subject. There's more to this than meets the eye! Actually, just recently have been tweeting on the subject :)
First of all, I'd strongly recommend localization to be done within the UI projects. You may have several UI projects, and not necessarily all of them will be localized. Your core projects should be agnostic toward this subject. The exception to this rule is if you use DataAnnotations. Imagine that you have some UI models that are utilized in all UI projects. You may annotate the members with Display and ValidationAttributes.

Anyhow, in solutions where you have only Web projects (as it is the case here), then applying localization becomes much easier. Guys from Asp.Net did a great job in this regard. By using the `IStringLocalizer` (which is registered if you have added the localization services to MVC), all you need to do is inject the interface wherever you need, and use it to localize your "free texts". Ideally you will do this only in the views, and eventually in the controllers, and very rarely in your view services. But localization/globalization is not just that, it encompasses the following:
- Localization of your "free text" string.
- Localization of the member names (DataAnnotations here are very useful).
- Localization of the validation messages.
- Localization of exception messages
- Localization of framework generated messages. Identity for an example, generates error messages for various invalid login scenarios. But, not always these messages are intended for the end user, so you should find a way how to segregate different types of messages.
- Regional settings. Here you have decimal formats, decimal/thousand separators etc.

Some problems even are caused by the existing standards as well. DateTime formats for an example. Configuring the date picker in some occasions can be a nightmare :) Browsers by standard read the OS'es regional settings to configure the date formats, and based on the Javascript library you're using, it might be propagated to the control as well. For an instance, if the user's Windows is using the English language with US regional settings (which mostly do), but have selected a different language on your site, then your app send the data in one format, but the UI control expects in different one. All of these issues one way or another has appropriate solution, but it can be painstaking task.

There are more details to all this, that right now I can't remember of. Anyhow, this is long subject, and I don't know if the maintainers want to tackle it in this project. Maybe another project which demonstrates all of this would be smarter move.

**Comment by abdalhadi** [comment]
Many thanks for replay,  i already implemented the localization in the presentation layer, and for handling some business validations in core or data layer, i use custom exception with specific code for each exception, so i can handle it in the presentation layer, and return meaning full message for the client.
