### ISSUE TITLE
Confusing comment in Order entity class or missing method?

### ISSUE THREAD

**Issue by storms-lab** [dotnet-architecture/eShopOnWeb#448]
![image](https://user-images.githubusercontent.com/51679664/89577557-dbf2aa00-d7fe-11ea-81f7-b25c76ea4c2c.png)

The comment in Order.cs above the list of OrderItems is very helpful, however also confusing because there is no method called AddOrderItem() as it suggests. Obviously it is not needed in the current eShopOnWeb project, but perhaps a method could be added to illustrate the point? And maybe to make use of it, the PublicApi could be expanded to include Orders? I personally am using this project as a reference for building a web service that is an API without a Web component.

EDIT: I don't yet have the best understanding of how everything in eShopOnWeb works or its direction, so forgive me if any of my suggestions are irrelevant.

**Comment by fiseni** [comment]
The comment is just leftover from some previous implementation. This is a great example to demonstrate why comments sometimes can be counterproductive.

In this case, we no longer have `AddOrderItem` method since we're accepting all items while creating the order (as a constructor parameter). Once the order is created, no longer you should be able to add items. You can add/delete items from the cart, and once you confirm and proceed to the payment, the order is created based on whatever is in the cart, Makes sense?

**Comment by storms-lab** [comment]
To be honest I haven't looked at this project in several months, but yes, I think that helps quite a bit. I'm excited to watch the overview video that was added to the Readme. That will help me get back into it in the coming months.
