### ISSUE TITLE
Violation of the Namespace Guidelines?

### ISSUE THREAD

**Issue by SeanStayn** [dotnet-architecture/eShopOnWeb#464]
Hey,

the Microsoft Namespace Guidelines and the Gendarme Rules state that a namespace depth of 4 levels should not be exceeded. 

[Microsoft Names of Namespaces](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces)
[Gendarme Rules](https://www.mono-project.com/docs/tools+libraries/tools/gendarme/rules/naming)

In this project a maximum namespace depth of 5 is reached. 

In our company this rule is strictly followed.

What are the possibilities to both achieve a maximum namespace depth of 4 and to be compliant with this Clean Architecture reference project?

With kind regards
Sean

**Comment by ardalis** [comment]
Namespaces in this project map to folders pretty much everywhere. If you don't want that much nesting, you can simply collapse some of the folder structure. For instance:
`namespace Microsoft.eShopWeb.ApplicationCore.Entities.BasketAggregate`

could be
`namespace Microsoft.eShopWeb.ApplicationCore.BasketAggregate`

and nothing would need to change otherwise. Apply the same approach everywhere. You may end up with more things in your higher-level folders, but that's the tradeoff with following the less-nesting rule.

**Comment by SeanStayn** [comment]
Thank you!
