### ISSUE TITLE
[Feature] Adding eShopOnSPA (Angular) Example

### ISSUE THREAD

**Issue by yehia2amer** [dotnet-architecture/eShopOnWeb#48]
First of all thanks a lot for this great and very useful repo 💯 

It will be Great to Add an eShopOnSPA (Angular) Example to this Repo without all the complications of microservices and containers in [here](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Web/WebSPA)

**Comment by CESARDELATORRE** [comment]
Thanks for your feedback!
This repo focuses on microservices/containers as the main feature. 
I think that feature would be a better fit for eShopOnWeb which currently focuses on plain ASP.NET Core MVC and Razor in vNext, here:
[https://github.com/dotnet-architecture/eShopOnWeb ](https://github.com/dotnet-architecture/eShopOnWeb )

Please, submit that feature request into that repo (https://github.com/dotnet-architecture/eShopOnWeb), if possible.

However, my particular team within the .NET team doesn't focus a lot on pure web/JavaScript development, like Angular4 or ReactJS, so this won't be a priority for us.
It would be great if the community would like to do that. Migrate the SPA client from eShopOnContainers to a simpler 3 Tier application under eShopOnWeb.
But, for that, it'd need to add ASP.NET Web API Services, too.
The current eShopOnWeb is a monolithic deployment web app with no REST services.
Any effort from the community here in regards ANGULAR4 would be very much welcomed! :)

**Comment by ardalis** [comment]
An Angular app version of this would be a welcome community addition. It would require some exposed API services, which might be best added as a separate PR.

**Comment by natarajkt** [comment]
I would love to contribute with API services

**Comment by jeremiahflaga** [comment]
Hi @ardalis , @natarajkt , @mohjache , 

This might be a dumb question but it's hard to find answers for this kind of question. In this sample project, eShopOnWeb, if I want to put authentication in the API part, should I create a separate AccountController for that? Or I can reuse the exisiting AccountController in the MVC part of the project?

Thanks!

**Comment by rafsanulhasan** [comment]
I am keen do work on this...

**Comment by jeremiahflaga** [comment]
Hi @rafsanulhasan , I would really love for this project to have API services because I'm planning to use this project when learning frontend javascript technologies such as Angular, ReactJS, and VeuJS.

**Comment by CESARDELATORRE** [comment]
We already have an SPA web app (using Angular) in eShopOnContainers as it has the microservices already.
Take a look here: https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Web/WebSPA

Deployment:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/06.-Setting-the-Web-SPA-application-up

It you want to create a monolithic Web API service consumed by an SPA app, you could re-use the SPA client side from eShopOnContainers (although it is not exactly the same compared to eShopOnWeb), but it wouldn't be very difficult.
However, we'd welcome folks from the community to do it in a PR. We won't invest more on SPA (Angular/JS) out of eShopOnContainers, since it is not our main goal and folks already have that SPA sample in eShopOnContainers.


Another possibility would be to do it here with REACT... :)

**Comment by CESARDELATORRE** [comment]
And btw, in case someone does it, it should take a similar approach than current with the Razor app and MVC app, so both re-use the same "internal" layers (ApplicationCore/Domain and Infrastructure).
Therefore, there should be a new ASP.NET Core Web API project based on those internal layers, pretty thin in code because of that.

Then, an additional project for the SPA app (either Angular or ReactJS), so it is clear it is just a client app. 
I think that's clear, if we segregate the responsibilities.

**Comment by CESARDELATORRE** [comment]
Another cool possibility instead of Angular or ReactJS: 
BLAZOR, everything in C#, even the client SPA side! :)

https://blazor.net/docs/get-started.html 

Note that BLAZOR is still experimental, not for production, though.

**Comment by jeremiahflaga** [comment]
Hi @CESARDELATORRE , thank you so much for your response.

You are right. The API services can and should be on a separate project :) Thank you for that.

And thank you for the info about Blazor. It's a very good project I think. I gives us the ability to use C# and .NET everywhere. I hope it will become popular and will be used by many in production.

**Comment by mdrewanz** [comment]
@CESARDELATORRE , in order to use BLAZOR, would it be the same approach as the monolithic or more towards the one used in eShopOnContainers?

**Comment by efleming18** [comment]
I'm going to close this issue as a Blazor version of this [is in the works](https://github.com/dotnet-architecture/eShopOnWeb/issues/343).

**Comment by punkouter2018** [comment]
This is good since I learn alot more from this than eShopOnContainers since you get bogged down in getting all the images to work together.
