### ISSUE TITLE
How to make joins with repository pattern?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#485]
I can see the beauty of repository pattern here. In this repo all are straight forward entity reads. What if I need to make a join between entity? Any good example of joins with repository pattern?

**Comment by fiseni** [comment]
I think you posted the same question [here](https://github.com/ardalis/Specification/issues/64), and there was a short discussion.

Briefly, the `Include` is already a join operation. When using the aggregates, the idea is to retrieve the aggregate as a whole, apply the required changes, and persist it as a single unit. This is required in order to preserve the consistency of the aggregate. On the other hand, when you just querying some information and you don't need to mutate the state, you can bypass the domain model completely. You can create complex custom queries and project the results directly to various dtos or view models ready for consumption.
