### ISSUE TITLE
Towards a better understanding of buyer/user

### ISSUE THREAD

**Issue by FlorianTh2** [dotnet-architecture/eShopOnWeb#491]
i have a sequence of questions regarding the User/ApplicationUser/Buyer and i hope you can help me on the way of understanding. I am new to the Clean-Architecture-Approach. I have already read a lot of (closed) issues but at some point i did not get any further.

1. Is Buyer an abstraction of ApplicationUser or does it belong to applicationuser (like e.g. posts belongs to a user, todoItems belongs to todoItemsList, ...)? Based on other issures i am 99% sure the buyer is an abstraction of applicationuser. This questions is just to be clear here (maybe for furture readers also). 

2. Why is Buyer defined in the domain but not added to the context/database (see [here](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/CatalogContext.cs) ) Because it is still an abstraction and we use it only as a kind of placeholder for ApplicationUser?

3. Why is Buyer included in the context/database in the partner-repostiory eShopOnContainers ( see [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs) )?

4. Buyer properties
	4.0 What exactly is stored in the Buyer-property IdentityGuid ( see [here](https://github.com/dotnet-architecture/eShopOnWeb/blob/28af1642f6405c04f0af71fd16dceaed53da627c/src/ApplicationCore/Entities/BuyerAggregate/Buyer.cs) )
		- userName? (i read this out of the code somewhere)
		- or email? (i read this in one issue i guess)
		- or applicationUserId? (implied by the name)
	4.1 In general: can i store in Buyer-property IdentityGuid everything that leads to a unique ApplicationUser?
	4.2 The Buyer in this repo is not present in the db. Why there are properties like payment method? I mean buyer is not in dbContext/database so isnt it useless?
	4.3 Why not add buyer properties directly to the "proper" (identity) ApplicationUser (in the infrastructure)?

5. So Buyer is not present in the database. Why do we need the Buyer in general? I mean we could write the IdendityGuid (like in buyer: see [here](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/BuyerAggregate/Buyer.cs) ) everywhere (in order, in basket, ...) instead of buyerId or did i miss something?

6. Is it good practice that e.g. orders have a prop buyerid but no fk-constraint? For Example Orders does reference BuyerId ( see 
[here](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/OrderAggregate/Order.cs) ). Since there is a guard-clause it is ensured that buyerid is not null but i dont know (?). I know we have 2 contexts / 2 different databases for catalog and identity and because of that it is difficult (maybe one could create a buyer everytime where is a applicationuser created but i dont think that approach is really scalable) to implement a FK.

7. Since we have no FK-constraint relating the user (buyer) in general, how can i (e.g.) delete all ressources of a user (e.g. user is deleted)? Do we have to hardcode a query for each sql-table + searching + deleting all rows in this table that includes a user-id since DeleteBehavior.Cascade is not possible? For this specific repository lets say we want to delete all orders if the user is deleted (and maybe in 10+ tables too that contains user-related ressources) (i know it is not so realistic, but yea).

8. Why is the user in domain called buyer and in infrastructure applicationuser (i mean in general i can understand, but ...) and not like DomainUser (Abstraction of IdentityUser) and InfrastructureUser (-> IdentityUser)

9. Currently in this repo i cant see a audit-approach like e.g. createdAt, createdBy, updatedAt, aupdatedBy maybe via a IAuditable-Interface. Lets say i want to override context.SaveChangesAsync() -> should i store that with a fk-constraint to buyer/user or just with id (of buyer/user) and why?

10. How can we get deep user-realted data like: Give me all orders of users with Role "Admin"? Is that even possible without fetching all rows into memory? I see the problem that we need to work with 2 contextes and i dont know how to manage a query like that.

11. How can we manage something more or less simple like "dbContext.buyer.orders" / "dbContext.users.posts"? ApplicationUser lives in a different db and buyer does not have the right navigational properties or does event exist in the catalogContext. Or is this just not possible with clean-architecture?

Thanks in advance.

**Comment by ardalis** [comment]
Some answers:

1. Buyer is meant to model details of the Buyer in the domain model. A Buyer or Customer has a lot more to model than a User, typically, and in this sample Identity/Auth concerns are kept separate from the domain model and only connect by the applicationUserId GUID (which Buyer has).

2. Buyer isn't in the database in this sample just because it's a sample and none of the sample's functionality required it. With more features, no doubt Buyer would be in the data model.

3. I'm guessing because there are features that necessitated it.

4. IdentityGuid is the applicationUserId Guid as a string.
4.1 You should just store the applicationUserId Guid as a string.
4.2 It's there to show how an Aggregate works. A future feature might add payment method selection to the checkout process, in which case the rest of the persistence pieces would no doubt be added to support the feature.
4.3 Because (as you point out) that lives in Infrastructure, which is only for non-domain code that's tied to specific implementation details. Buyer properties are not Identity/Auth specific nor are they coupled to a particular implementation and thus should be modeled in the domain in the ApplicationCore project.

5. You're not wrong. Buyer's shown in the model mainly for educational, not functional, purposes in the app's present state.

6. Yes, because Buyer is not part of the Order aggregate. A Guard against a null/empty buyerId might be worthwhile. Most likely once Buyer evolved to the point where it was being persisted, Order would reference `int buyerId` rather than the string it's using now. Right now it's in a bit of an intermediate state. It's probably worth fleshing out Buyer so the sample is better.

7. Yes you would need to implement some specific logic since relational integrity doesn't span databases and string-based keys won't do cascade deletes for you. As you note this isn't a typical or common occurrence. There's some business decision to be made as to what should be deleted vs. archived as well. Just because a user is deleted doesn't mean that all of the Orders that were shipped to that customer last quarter should disappear and sales reports for the company altered, right?

8. This question sounds a lot like previous ones. The Buyer is a different abstraction from an ApplicationUser in that the former represents things of interest in the context of an online store and the latter is purely an abstraction for authentication/authorization purposes. There's often a 1:1 correspondence between them, but they're not the same thing.

9. There are several ways to implement audit functionality like this. One is with database triggers or default values on columns. This works well for pure DateTime fields like CreatedAt but not as much for CreatedBy, which requires more information. For audit trails that include more context than just times, I prefer to use events. You can trigger events for any activity you would like to audit and then use event handlers to store the details of the events however and wherever you want. This could be in a table in the same database, in which case you could add FK relationships if you wanted, or it could be in a separate data store. Generally the FK relationships on the audit table are of limited value, in my experience, so I'm fine not to include them. Yes, that means if you delete a Customer you'll still have records in the audit table saying that user jones modified customer 123 on DATE but that data is still correct and potentially useful even if customer 123 no longer exists. And in fact the last entry in the audit might say that user blackhat deleted Customer 123, which might be good to know if you were trying to recover from an errant deletion.

10. This would be easy to do using the Identity dbcontext to get all the users in the role, and then the application dbContext could fetch orders for them. However, it's also the kind of thing that's easily done with SQL or a stored procedure, and I wouldn't hesitate to use the right tool for the job in this case. Typically when you're trying to get data like this, it's not because you want to work with each Order or Buyer as a domain model type. It's for read-only reporting. So don't try to force that through your domain model. Just write a query and return the results (as a read model if you need it).

11. This sounds like a variation of question 10. If you are just looking for readonly data, use whatever tool is best for the task. That might be a dbContext and domain entities or it might be a custom query returning a DbSet or custom read model with just the columns you care about. If you're just looking for arbitrary data, that's a different problem than if you're trying to model the domain in order to encapsulate business logic and behavior. Clean architecture and DDD tend to focus mainly on the business logic and encapsulation of behavior. When you just need data without business rules and models, use a read model and whatever query fits your needs best. Don't try to force all your querying needs through entities and aggregates.

11b. Now, if your reason for wanting to get to a buyer's orders is because you have some business logic you want to run on them, like there's a new rule that says a Buyer will get 10% off their 11th order, then you should be able to model that in your domain somehow. In that case a Specification can probably give you what you need.

HTH.

**Comment by FlorianTh2** [comment]
Thank you for your outstanding answer. I really appreciate it. It helped / helps me alot. I had a kind of wrong interpretation of the buyer - ApplicationUser relation. Thank you for correcting me. First i want to go into your answers:

6.:
> It's probably worth fleshing out Buyer so the sample is better.

I really like it that you included buyer. I think it gives a hint how to properly continue after the init (intermediate state) repo. Sure it may lead to some questions. But i dont know if thats a bad think in general.


7. :)

11b: Recently i watched your (recorded) live-session (on [youtube](https://www.youtube.com/watch?v=vRZ8ucGac8M&ab_channel=Ardalis) ). In this session you mentioned and explained (amongs other things) the
- specizication pattern with generic repository
- repository pattern in generel
- unit of work pattern
- aggregate pattern
- guard-pattern.

Your work is truly amazing. Try to keep it up.



Based on your answers new, related, questions came up. Maybe you can answer them aswell.


12. topic: buyer creation (12.1+12.2 are really realted)
	12.1 When exactly is the buyer-entity created + persisted (assumption: app tries to leave intermediate state) ? Is the buyer-entity directly created along with the ApplicationUser during the register-process?

	12.2 How is the buyer created?
	- Should the IdentityServer (e.g. based on asp.net core identity) 1. create the ApplicationUser via the identityContext by e.g. invoking _userManager.CreateAsync() and 2. create the buyer-entity inside the same controller-action via the applicationContext? Or in the same approach create the buyer maybe by override the _userManager.CreateAsync() and attach the implementation for buyer-creation?
	- You mentioned events. Or should we create the buyer in reaction to some identity-creation-event somehow somewhere else?

	12.3 Do you know a repo in which one can see a kind of working register-process using the clean-architecture-approach with some kind of user-abstraction like buyer?


13. How should the register-authentication-process be, if there are some required fields 1. according to your identity-provider BUT ALSO 2. required fields according to you user-abstraction (e.g. buyer)? Does the identityServer also have to ask the user directly in the register process regarding (2.) the required fields of the user-abstraction (buyer)? So we have to kind of hardcode the required fields of the user-abstraction (buyer) into the identityServer to make identityServer retrieve this field of the user? Or is the user LATER confronted to input some more user-specific data to use that service (e.g. here the catalog-service)?

14.
> The Buyer is a different abstraction from an ApplicationUser in that the former represents things of interest in the context of an online store and the latter is purely an abstraction for authentication/authorization purposes.

If the user wants to register (start of the authentication) i like e.g. to get his forename and lastname to be able to greet him e.g. after he finishes the process of authentication. Where should i store this information (forename/lastname) -> in the identityServer/domain-model/both?
	- Currently i would maybe implement it in the domain-model (only). Reason: if i store it only on the identityServer and have to exchange the identityProvider, i have a problem. Am i on the right track here?

15. Where to store clear identity-information if the buyer has to access some elements of the IdentityProvider frequently e.g. the email or in general this information (e.g. email) is considered to be as a part of the domain model? Should i store this information (e.g. email) additionaly in the domain-model (buyer) or should i always do a join (buyer-ApplicationUser) via the applicationUserId to get user-data from the identityServer and then return the email of the ApplicationUser-data?
	- Difference to 14: email address must be stored on IdentityServer (at least here) -> forname/lastname can be stored there (theoreticly)
	- I guess, currently i would store the email at both places since it has to be stored on IdentityServer but i consider it to be part of the domain-model. Am i right here? (i really dont know)

**Comment by MG110417** [comment]
Hello,

I have a similar questions related to Buyer Aggregate. Currently "Add to Cart" functionality generates a BuyerId Guid. Now lets say that we do create a Buyer Data Entity and save to database, at what point this operation would happen if you are allowing guest checkout? For example, I have a scenario that I need to allow Guests to add items to cart, after that when they hit checkout, I need to ask them about FirstName, LastName, Email, Phone# etc (that information will be saved into Database). Now the problem is already created with the BuyerId and buyer was added later. Can you please provide some information how would you handle this usecase?

Thanks.

**Comment by ardalis** [comment]
Sorry for the long hiatus.

@FlorianTh2 Thanks for the kind words! Here are some more answers. This is somewhat hard to track with so much per comment - in the future please ask unique questions per issue if there's more than 1 or 2. Thanks!

12. Creating a Buyer. The `Buyer` aggregate isn't actually created anywhere in the sample at least at the time of your question, so your confusion is understandable. Currently a `BuyerId` is set on a `Basket` and then later used for an `Order`.

The question is really, where *would* a `Buyer` be created and persisted. Some options:

- When a user registers. This is probably the obvious place to do it. There probably isn't a lot of cause for folks to register with an eShop if they're not planning on buying anything.
- When a user checks out. If anonymous/guest checkout isn't supported, it could be required to register; otherwise it could simply be suggested as a convenience so payment methods, order history, etc. would be available when the user returns.

In any case, creating and persisting the Buyer should be trivial. Just instantiate it, configure its properties, make sure its UserId maps to an existing Identity UserId, and use a repository to persist it.



> 13. "Or is the user LATER confronted to input some more user-specific data to use that service (e.g. here the catalog-service)?"

Yes that's how I'd model it. Let them register and then ask them to create a Buyer account with more details. Or just *don't* require anything but a UserId in order to create a Buyer, in which case the base record can be created on registration and any additional fields are just updating that existing record. This is more of a business decision than a technical one in a real app, since the goal is to make user abandonment as small as possible. So make the process as easy and streamlined as possible.

14. Where to store firstname/lastname: on the identityuser or on the Buyer/Customer?

Personally I would store these details in the domain model, so in this example that would be on the Buyer most likely. If you're already supporting identity solutions like OIDC that can provide name information you might choose to keep that with your identity model, or just populate the data into the Buyer during registration (my preference).

15. Yes if you need it in the domain model, duplicate it. Also you may realize that many Buyers have multiple email addresses just like they may have multiple OIDC providers. The web sites that I find more enjoyable to use let me associate my account with more than one email and/or OIDC provider so I don't have to remember which one I used for that particular site. Giving the user a 1-to-many option for contact details like addresses, phone numbers, emails, etc. is usually a good design in my experience.

**Comment by ardalis** [comment]
@MG110417 I think I would have a separate GuestAccount or AnonymousBuyer entity or similar which would capture and persist details of anonymous/guest users. If/when they are promoted to known Buyers, you would simply use this entity to populate the Buyer aggregate and persist it there, perhaps deleting or otherwise invalidating the guest/anonymous account.
