### ISSUE TITLE
What multiple projects do I run to use the admin section?  

### ISSUE THREAD

**Issue by punkouter2021** [dotnet-architecture/eShopOnWeb#501]
I tried both ways mentioned but not clear exactly which projects to run . I assume the Web project and the API project but when I click the UPLOAD button in the admin section it does nothing and there is a client side error. HELP

**Comment by ardalis** [comment]
You should just need the BlazorAdmin project and the PublicAPI project. The eShopOnWeb web project isn't necessary but you can run it, too, if you like.

**Comment by BlazeDog** [comment]
One problem I had was with the ssl certificate.  I could tell the localhost:5099 calls were failing from the admin page by looking at the console.  When I looked at launchsettings.json, there are two profiles, PublicAPI and IIS Express.  I was looking at this because I had never used Swagger and was used to postman.  So, I was not sure how Swagger and the API co-existed.

When I launched PublicAPI from VS as PublicAPI (not running through IIS), it prompted me to accept the certificate.  After that, the admin page worked via dotnet run where it was not before.  Dotnet run never gave me the prompt VS did.  I found your issue when trying to resolve mine.  It sounds similar.
