### ISSUE TITLE
Seperate Domain.Core and Domain.Application in different project

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet-architecture/eShopOnWeb#505]
Hi,
I want to separate `ApplicationCore` project to `Domain.Core` and `Domain.Application`. In this situation, interfaces for both infrastructure and services should place in Core or Application layer? And Infrastructure should reference to Core or Application?

**Comment by fiseni** [comment]
I would suggest naming the projects `Domain` and `Application` (or just `App`). You may also create a solution folder named `Core`, and place both projects there.

The `Infrastructure` project most probably will have to reference both of them. It will reference `Domain` since the entities are there; and might reference `Application` since UI or view models may live there, so if you're projecting query results directly to UI models you'll have to access them.

As for the Interfaces, it depends on the context, not necessarily they all will be in `Domain` or `Application`. If a given service is required in the domain model, then you'll keep it in the `Domain` project, otherwise, you can take it out wherever is required.

Check this [answer](https://github.com/dotnet-architecture/eShopOnWeb/issues/165#issuecomment-440737177) for some other details.

**Comment by mehdihadeli** [comment]
@fiseni Thanks.
