### ISSUE TITLE
Address potential security concerns with uploading to `wwwroot`

### ISSUE THREAD

**Issue by IEvangelist** [dotnet-architecture/eShopOnWeb#537]
While I do not believe that this is an ["unrestricted file upload"](https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload) issue (as there is an [authz check](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Controllers/FileController.cs#L17-L20)), we have community members expressing concern. We should fully vet this upload functionality from the perspective of security.

_Concern_:

- https://twitter.com/willdento/status/1405703739911000070?s=20

Evaluate [`Upload`](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Controllers/FileController.cs#L15) functionality for potential security concerns. Attention @ardalis and @nishanil - thoughts on this?

**Comment by ardalis** [comment]
It would probably be safer to do the upload to another location, possibly blob storage, and then have some approval workflow step that would be involved before the files would move to wwwroot for hosting (assuming they've been vetted as image files for the product catalog, in this sample's case).

**Comment by nishanil** [comment]
What are your thoughts on just disabling the upload functionality and add a default image for every new product? Considering this is a reference sample, we shouldn't be aiming for a complicated implementation at the same time not recommending bad practices. We can drop in our recommendations in the comments for prod scenarios instead of implementing them.

**Comment by ardalis** [comment]
Sure, that would be fine, too.
