### ISSUE TITLE
How to understand ApplicationCore.Entities in relation to persistance

### ISSUE THREAD

**Issue by acambule** [dotnet-architecture/eShopOnWeb#538]
Hello,

I'm quite new to .NET Core/Ef and the world of web development, as professional desktop application developer. Our next project is a .NET Core saas. So i got introduced and started to dive in. I started myself to take a look around and learn more and found this one, but it is a lot different than our approach, and i try to understand.

Given that in the end we want to save all data into a relational database (makes it easier for the conversation).

In our approach we use Ef with code first and/or fluent api to declare the `database models` and how they should look like in the  database in the end. 

In this approach i miss this information, that makes me feel a bit uncomfortable as i do not understand how the datastructure in the end looks like and how the relations are met, or where the conditions are setup.

Are the entities in \entities folder user for Ef migrations? If so, why aren't any annotations used?
if not where is the structural information setup?

And another last question. E.g. a customer can have a delivery address and a billing address. I want to define a address class and use it for both, so that at the end the database table has these duplicated with different names. 
For this i would have declared somethin like

```c#
public virtual Address DeliveryAddress { get ; set; }
public virtual Address BillingAddress { get ; set; }
```
and a fluent api configuration.

How would i do this now. Still the same?

Thanks and regards
Antonio

**Comment by ardalis** [comment]
Hi Antonio,

If you haven't yet, I recommend reading the eBook that goes along with this sample. If you have access to Pluralsight, you might also check out my course on N-Tier Apps in C# which describes the differences between data-centric architecture (with which you seem to have more experience) and domain-centric architecture (how eShopOnWeb is organized).

The entities in ApplicationCore are the types used by EF Core for migrations and data access at runtime. They don't have annotations because one of the goals of this design approach is for the entities to be [persistence ignorant](https://deviq.com/principles/persistence-ignorance). Instead, the specifics of how the entities are mapped to the database are stored in the [config folder in the data folder in the infrastructure project](https://github.com/dotnet-architecture/eShopOnWeb/tree/master/src/Infrastructure/Data/Config). This approach keeps the entities from becoming cluttered with details that don't matter to their OO design and behavior, too (but which certainly do matter at runtime when persistence occurs).

Using a [value object](https://deviq.com/domain-driven-design/value-object) for something like Address is a good approach. I cover these in my Pluralsight course, [DDD Fundamentals](https://www.pluralsight.com/courses/fundamentals-domain-driven-design), but you can also learn about value objects from free online resources easily enough. To use them with EF Core, you will want to learn about [owned entity types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities).

Hope that helps.

**Comment by acambule** [comment]
Hi ardalis,

thanks that helped a lot.
