### ISSUE TITLE
Entity validation in constructor

### ISSUE THREAD

**Issue by EyalIsr** [dotnet-architecture/eShopOnWeb#542]
Hi,
I would like to ask general question, with regarding DDD and show an example from eShopOnWeb.
In `Order` entity there's a public c'tor with some `Guard.Against`... expressions that validate the state of the entity before initialize it - and it'll be called on adding (new) Order.
My question is: isn't this validation should be enforced on fetching `Order` as well? meaning - when going the "fetching way", i.e. getting an `Order` from a repository the parameterless c'tor will be used and therefore those `Guard.Against`... won't be called.
Is it a good practice to add those to the default private c'tor?

Thanks,
Eyal

**Comment by ardalis** [comment]
If you're following DDD and you have a bounded context that "belongs" to the app, you can generally trust that anything you persist in a valid state, will still be valid when you retrieve it. If this assumption holds, then you don't generally need to validate entities as you retrieve them from persistence. If you don't trust your persistence layer, perhaps because it's not solely a part of your bounded context, then it might make sense to validate them when you retrieve them, too.
