### ISSUE TITLE
BasketService is in Web project and OrderService in Infrastructure project. Why not in Core Project?

### ISSUE THREAD

**Issue by Ka-Marius** [dotnet-architecture/eShopOnWeb#59]
BasketService and OrderService has some Business logic, but these services are not in Core Project (one is in Web, another in Infrastructure project). I can't understand why. Can You please explain me?

Many thanks.

![image](https://user-images.githubusercontent.com/24824595/31851196-8379a996-b669-11e7-917f-3288da3aeb38.png)

**Comment by yarrgh** [comment]
The services in Web depend on the ViewModels in Web, which is why they are in Web. 

My opinion is that something like AutoMapper should be used in the controllers to convert to ViewModels and the services shouldn't produce ViewModels or even interact with ViewModels. If this was the case, they could probably be moved to ApplicationCore (unless I missed another dependency on Web)

OrderService in Infrastructure doesn't seem like it needs to be there and could be placed in ApplicationCore. I only just quickly glanced through it though.

**Comment by ardalis** [comment]
I agree with yarrgh; it's on my list to refactor. The reason they are there now is due to inherited code and the fact they return view-optimized data types. But it's a good question and one I plan to address shortly.

**Comment by ardalis** [comment]
FYI, in the most recent updates to the sample, the non-UI work that was in the `BasketService` was moved into a service defined in `ApplicationCore`. The `CatalogService` is pretty much all about UI, and the `CachedCatalogService` works closely with it, so I've left these in the UI project(s).

I don't have AutoMapper installed in the solution at this time, but I could see adding it. If someone wants to PR that, I would probably accept it.
