### ISSUE TITLE
Clarifications about Tests

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#637]
I was going through the tests and here are my observations.

1. Unit Test - All domain entities logics can be unit tested here. Specification, Services, Mediator Handlers. We will be using mock if needed.
2. Integration Test - Repositories are tested here with InMemory SQLite Database.
3. Functional Test - End to End flow from API till database using InMemory SQLite Database.

So my questions are,

Mediator handlers will anyways need Repositories in most of cases so instead of mocking them in unit test can Mediator handlers be tested as part of Integration test with InMemory SQLite database?

And what about Domain Services, this also needs to mocked in unit test or can be covered in integration test?

Integration test means testing integration between handlers, repositories, external services..? or integration of our code with database?

Please assist.

**Comment by ardalis** [comment]
Your observations seem accurate to me.

There aren't many MediatR handlers in this solution. We show one just as an example of the pattern in the `GetMyOrdersHandler` in the Web project. That particular handler basically does two things:
1) get the orders
2) map them to an `OrderViewModel`

Assuming you already have tests for your data logic, you don't really need to test it again here, so a mock works fine. All you really need to test is the mapping. There's no need for or benefit from using an integration or functional test here, IMO, since they will just be slower and more brittle but won't test things any better than a unit test (with mocked or fake inmemory repository).

What about domain services? These should be unit testable 100% of the time because they're in your domain. If you do things properly, everything in your ApplicationCore (domain model) should be unit testable.

Integration test means both testing how multiple instances in your system interact as well as how your code interacts with infrastructure (database, file system, external APIs, etc.). In most apps that follow Clean Architecture the majority of integration tests will be the latter kind.

Especially if you are building an API, functional tests can be used to test integration of the whole system, perhaps with test versions of certain dependencies (like email sending, credit card charging, etc.)

Hopefully that's helpful.
