### ISSUE TITLE
Handling external validation rules in domain handler compare to command handler

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet-architecture/eShopOnWeb#670]
Hi @ardalis,
I watched your [video](https://www.youtube.com/watch?v=x-UXUGVLMj8&t=4515s) and your [article](https://ardalis.com/immediate-domain-event-salvation-with-mediatr/) about handling some domain rules with some dependency with domain handler. What is the advance of this approach compare to handling this validation rules for example in our command handler before calling our domain model action?
Suppose I want to create a product that has a `categoryId` and I want to ensure passed `categoryId` is valid in my DB, Should I handle this with using a `ProductCreatingEvent` and `ProductCreatingEventHandler` and in my handler check for existing this category in the database? 
Second approach is checking this validation in my `CreateProdctCommandHandler` before doing ant domain action. 

The second approach is easier in my mind. What is your opinion?

**Comment by ardalis** [comment]
Hi Mehdi,

You have a few questions here. There are tradeoffs to different approaches, and I can share my personal opinion but even I make exceptions where I think it makes sense.

My *default* approach is to perform *structural* validation on the user's inputs as early in the request as possible. That means checking that, in the case of APIs and Request DTOs, required fields are present. Numeric values are in a valid range. Etc. I liken this to a clerk being handed a form that someone has filled out at a customer service desk. They can quickly scan it to ensure that the right sections have been completed before handing it off to the person who will perform the task. Problems with the message shape or structure are not exceptional - they're expected. They should be dealt with using result types and conditional logic, not exceptions.

The domain model is another story. It doesn't know about the UI or how requests are formed or any of that detail. It is meant to model business processes, rules, and concepts. It should be designed in a way that ensures it cannot be put into an invalid state. If certain values are required, then the object's constructor should require them, and should throw an exception if null values are provided. If a method that would mutate state is passing in something nonsensical, then that too is likely an exception, since the application should never have given the user the opportunity to perform that action.

Now, in between the domain model and the API actions there might be commands, events, and handlers. These are completely optional and can add complexity as well as advantages. They might be modeled within the domain model, or within the Web project, or some combination of the two. Where they work with the domain model, they should ensure they're following the rules of the model, and if they don't, they should probably find the model raising exceptions as a result. Where they are performing validation of user inputs, they should find non-exceptional ways to pass back validation concerns (such as [Result](https://www.nuget.org/packages?q=ardalis+result) types).

HTH.

**Comment by mehdihadeli** [comment]
@ardalis Thanks for your guide
