### ISSUE TITLE
Swapping to the Development environment displays detailed information about the error that occurred.

### ISSUE THREAD

**Issue by AvtsVivek** [dotnet-architecture/eShopOnWeb#672]
I cloned [this eShopOnWeb repo](https://github.com/dotnet-architecture/eShopOnWeb).

I successfully got it to run with dotnet cli.

But when I am trying to [run on docker](https://github.com/dotnet-architecture/eShopOnWeb#running-the-sample-using-docker), I got into this issue.

I was able to build and run the app. But when I try to login, key in Email and Password, I get this error. 

Error.
An error occurred while processing your request.
Development Mode
Swapping to the Development environment displays detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

What am I missing? I searched but could nor find any one talking about this with respect to docker.

![image](https://user-images.githubusercontent.com/41255281/152636356-8a23425c-4a82-41fe-a130-a3c397f10464.png)

Raised the issue here as well.
https://stackoverflow.com/q/70996767/1977871

**Comment by michelcedric** [comment]
The reasons was propbably because, you not create the database and apply migration

1.  normally the code made that itself. It was the case for Catalog but not yet for Identity database.
2. I adapt to launch earlier the migrate database
3. in docker the developer page was not available, i also adapted that
4. The admin part in blazor only work in release mode (i not yet understand why)
