### ISSUE TITLE
What are your thoughts about passing prices as decimals in dtos

### ISSUE THREAD

**Issue by snax4a** [dotnet-architecture/eShopOnWeb#697]
Hi, I wonder if it wouldn't be better to store prices as long data type instead of decimals so they would be stored in cents or any smallest currency unit.

This is what Stripe is doing because it is supporting many currencies including zero-decimal currencies https://stripe.com/docs/currencies#zero-decimal

Is it safe to use decimals in dtos and serialize them to json numbers in the api response? Wouldn't be there any cent losses?
Most payment gateways are passing amounts in JSON as integers or decimal strings.

If I would like to support multiple currencies:
- should I use decimal data type in the code and only create a custom JSON converter and convert prices to strings or integers?
- or should I use long data type in the entities and bigint in the database? This option seems to be more complicated as some calculations like discounts and taxes require decimal values so it will require a lot of explicit decimal casting. Also the data in the database will be harder to read.

What is your experience regarding this?

**Comment by michelcedric** [comment]
HI @snax4a 
This repository is only a sample. In my personnal experience effectively seems to store amount in cent seems better to manage it.

**Comment by ardalis** [comment]
Decimal is the Microsoft-recommended data type for simple currency values and is sufficient for the needs of this sample. I'm sure there are domains in which it's better to use a different data type, but unless you're able to demonstrate a case where decimal isn't meeting your needs, it's generally a good starting point (and you should avoid float and double due to rounding issues, etc.). See here for more discussion on this: https://stackoverflow.com/a/1008830.
