### ISSUE TITLE
Error Handling in PublicApi

### ISSUE THREAD

**Issue by claudeHasler** [dotnet-architecture/eShopOnWeb#750]
In PublicApi Endpoints some errors are handled, for example when the specified resource could not be found:

```
public async Task<IResult> HandleAsync(DeleteCatalogItemRequest request)
    {
        var response = new DeleteCatalogItemResponse(request.CorrelationId());

        var itemToDelete = await _itemRepository.GetByIdAsync(request.CatalogItemId);
        if (itemToDelete is null)
            return Results.NotFound();

        await _itemRepository.DeleteAsync(itemToDelete);

        return Results.Ok(response);
    }
```

All exceptions which could be caused by DeleteAsync() are ignored (the delete can fail) and left to the framework to return. Is this a conscious design decision or a limitation of a  "demo project". In my own projects I have found that trying to properly return some value for each exception quickly leads to an explosion of code

**Comment by ardalis** [comment]
HTTP standards suggest that requests to work with a resource that doesn't exist should return a 404. Hence, this isn't exception handling per se, it's just following the HTTP spec by returning NotFound instead of an error or success response.

In general, it's best to have a global exception handler/middleware for APIs, so that you don't end up with the explosion of code you're describing. You can also leverage something like the Ardalis.Result package in your services so that things like validation errors can easily be returned from your services and then used by your API to return well-formatted bad request responses to the requester (with the details of which things weren't formatted properly).

**Comment by claudeHasler** [comment]
Thank you very much for taking the time to help me and so many others!
