### ISSUE TITLE
Please add .mobi and epub versions of the books in addition to the pdf versions

### ISSUE THREAD

**Issue by andrecarlucci** [dotnet-architecture/eShopOnWeb#77]
I just found the PDF version.
It would be really nice to use e-book readers for that.
Thanks!

**Comment by CESARDELATORRE** [comment]
We're working on it. We'll have it in eReader (.EPUB and .MOBI) a matter of days. :)

**Comment by abukres** [comment]
You can use Calibre. A free ebook converter.

**Comment by CESARDELATORRE** [comment]
We already published it as .MOBI and .EPUB as announced here:
https://github.com/dotnet-architecture/News/issues/8

Subscribe to the NEWS repo (clock on Watch) to get the news, ok? 👍 

Also published in the landing page:
https://www.microsoft.com/net/learn/architecture 

Either using Calibre or any other tool, it is a bit costly because of different layout size, etc. But we're making a few of them. 

Closing the issue. 👍
