### ISSUE TITLE
CQRS MediatR

### ISSUE THREAD

**Issue by marcrib** [dotnet-architecture/eShopOnWeb#82]
In this architecture, mediatR (Command/Handlers) are implemented in ApplicationCore?

Why Serivces in web project? (CatalogService)
Why not use auto mapper for model => viewModel ?

**Comment by yarrgh** [comment]
For Automapper, see the discussion in https://github.com/dotnet-architecture/eShopOnWeb/issues/59#issuecomment-338766899

**Comment by ardalis** [comment]
I can see adding MediatR as an option, probably side-by-side with existing Razor Page and MVC approaches so that developers can see how it's used and how it compares. I don't think I would add it as a separate project just because that becomes a maintenance issue as we update the project for new versions of .NET.

AutoMapper we could add, but I don't think it would add a lot of value. There's really not that much model-viewmodel mapping that is purely same property mapping which is where AutoMapper shines, and it adds one more dependency to the project. Again I could see adding it just so developers can see how to wire it up, but not because it's particularly useful here.

Why are services in the web project is a common question. Basically these are application services that return ViewModel types that are defined in the Web project (where they belong). Since the services return Web types (ViewModels) they too must be in the Web project. They basically exist to keep code out of controllers (controllers should be as thin as possible) and to provide a means for implementing caching using a decorator on the service interface.
