### ISSUE TITLE
CustomerOrdersWithItemsSpecification as glue in OrderController. How to unit test OrderController?

### ISSUE THREAD

**Issue by ChandanGhosh** [dotnet-architecture/eShopOnWeb#83]
As I was trying to see the FunctionalTests, I see it is difficult to unit test the OrderController index method as this method glue the CustomerOrdersWithItemsSpecification with new keyword while calling OrderRepository at line number 25. Can you advise what could be a possible way to unit test this particular controller method?

**Comment by ardalis** [comment]
Specifications are value objects with no external dependencies. As such, they don't typically make unit testing more difficult. Here's the line in question in this case:

```
    var orders = await _orderRepository.ListAsync(new CustomerOrdersWithItemsSpecification(User.Identity.Name));
```
If you wanted to *unit* test this method, you would mock the `IOrderRepository.ListAsync` method. Since that's not the method being tested, it doesn't matter what you send it, so if you're using Moq you could call it with a parameter of `It.IsAny<ISpecification<Order>>()` or something similar. The use of a new instance of a specification in the real code wouldn't interfere with this behavior (it would comply with the criteria of being any instance of the appropriate type).

I assume you've read my article, [New is Glue](https://ardalis.com/new-is-glue). It's cautioning against strongly coupling to types (by newing them up) that have infrastructure dependencies (directly or transitively). Value objects don't (and shouldn't) have such dependencies so they're generally not something you need to worry about using new with.

Finally, there's not much value in unit testing this particular method. It has very little complexity; about the only thing you would test would be that the mapping in the .Select call was correct (and that could be moved into a separate method or type). A functional test might be all that's needed for this method (and generally in ASP.NET Core I prefer functional tests over unit tests for controller actions). If you have enough logic in your controller that a unit test would be helpful, you probably have too much logic in your controller, IME.
