### ISSUE TITLE
[Book improvement] Book Feature Comparison Table Missing Containers

### ISSUE THREAD

**Issue by mattferderer** [dotnet-architecture/eShopOnWeb#84]
Sorry if this is the wrong place but the book does a great job detailing architecture.  On page 107, there is a features table which I think has a lot of value. Unfortunately it's only showing 3/4 of the methods you mentioned. Containers and Azure Container Service is left off. Did I miss something or is there a good reason to leave it off or could it just be combined with one of the others on the chart like VM?

**Comment by CESARDELATORRE** [comment]
@mattferderer - Good feedback. Adding @ardalis (Steve Smith) who's the author of this eBook.
I agree that since the content is also talking about ACS and Containers, it should be included into that table.
The reason might be because originally this ebook was focusing only on ASP.NET Core apps without containers, but then we decided to include containers. That table must be previous to the containers content.
In any case, Steve is "work in progress" updating this eBook in the upcoming months heading .NET Core 2.1 features, so this part could also be updated/improved. I think we should add:
- AKS (Azure Kubernetes Service)
- ACI (Azure Container Instance)

Btw, if you'd like to get more info about Containers and Microservices, read the .NET Microservices eBook here: https://aka.ms/microservicesebook

Thanks for the feedback! 👍

**Comment by ardalis** [comment]
Finishing up some updates to the book now; will look at getting this added, too.

**Comment by ardalis** [comment]
You can track progress on this here:
https://github.com/dotnet/docs/pull/4905

Closing out this issue now.
